Repository conda/conda, pull requests merged in 2018-04, with the labels that each got.

#7122 Import speedups
  conda/common/configuration.py
  conda/common/path.py
  conda/common/url.py
  conda/models/channel.py
Labels: Ready for Review, source:contributor

#7076 fix #7075 add anaconda.org search message to PackagesNotFoundError
  conda/exceptions.py
Labels: Ready for Review

#7120 clean up the formatting of help output
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/install.py
  conda/cli/main_config.py
  conda/cli/main_install.py
  conda/cli/main_remove.py
  conda/cli/main_search.py
  conda/cli/main_update.py
  conda/common/configuration.py
  conda/core/solve.py
  conda/exceptions.py
  conda_env/cli/main_remove.py
  setup.cfg
  tests/base/test_context.py
  tests/test_create.py
Labels: Ready for Review

#7131 fix #7107 verify hangs when a package is corrupted
  conda/core/path_actions.py
Labels: Ready for Review

#7152 fix typo in conda.fish
  conda/shell/etc/fish/conf.d/conda.fish
Labels: tag:shell

#7096 fix #7094 exit early for --dry-run with explicit and clone
  conda/misc.py
  tests/test_create.py
Labels: Ready for Review

#7060 add CondaError details to auto-upload reports
  conda/exceptions.py
Labels: Ready for Review, ¡blocking!

#7048 fix #7040 update tqdm to version 4.22.0
  circle.yml
  conda/_vendor/tqdm/__init__.py
  conda/_vendor/tqdm/_main.py
  conda/_vendor/tqdm/_monitor.py
  conda/_vendor/tqdm/_tqdm.py
  conda/_vendor/tqdm/_tqdm_gui.py
  conda/_vendor/tqdm/_tqdm_notebook.py
  conda/_vendor/tqdm/_tqdm_pandas.py
  conda/_vendor/tqdm/_utils.py
  conda/_vendor/tqdm/_version.py
Labels: Ready for Review, ¡blocking!

#7101 fish autocompletion for conda env
  conda/shell/etc/fish/conf.d/conda.fish
Labels: tag:shell

#7160 add http error body to debug information
  conda/_vendor/auxlib/logz.py
  conda/core/subdir_data.py
  conda/exceptions.py
  conda/gateways/connection/download.py
Labels: Ready for Review

#7133 resolve #4274 add option to remove an existing environment with 'conda create'
  conda/cli/common.py
  conda/cli/main_create.py
  conda/exceptions.py
Labels: Ready for Review

#7162 resolve #7061 remove pkgs/pro from defaults
  conda/base/constants.py
  conda/base/context.py
  tests/models/test_channel.py
Labels: Ready for Review

#6518 conda initialize
  .github/CONTRIBUTING.md
  .gitignore
  CONTRIBUTING.md
  MANIFEST.in
  appveyor.yml
  circle.yml
  conda.recipe/bld.bat
  conda.recipe/build.sh
  conda.recipe/meta.yaml
  conda.recipe/setup.py
  conda/activate.py
  conda/base/constants.py
  conda/base/context.py
  conda/cli/activate.py
  conda/cli/conda_argparse.py
  conda/cli/main.py
  conda/cli/main_init.py
  conda/cli/main_pip.py
  conda/cli/pip_warning.py
  conda/common/compat.py
  conda/core/initialize.py
  conda/gateways/subprocess.py
  conda/shell/cli-32.exe
  conda/shell/cli-64.exe
  conda/shell/conda_icon.ico
  conda/shell/condacmd/conda-hook.bat
  conda/shell/condacmd/conda.bat
  conda/shell/etc/profile.d/conda.csh
  dev/requirements.txt
  dev/start.bat
  dev/start.sh
  dev/test-requirements.txt
  setup.py
  tests/cli/test_main_info.py
  tests/core/test_initialize.py
  tests/gateways/disk/test_create.py
  tests/models/test_channel.py
  tests/test_activate.py
  tests/test_api.py
  utils/appveyor-install.bat
  utils/functions.sh
  utils/install.ps1
  utils/requirements-test.txt
  utils/setup-testing.py
  utils/smoketest.py
  utils/smoketest.sh
  utils/tester.bat
  utils/travis-bootstrap-conda.sh
  utils/travis-install.sh
  utils/win_build_env.cmd
Labels: Ready for Review, tag:shell, ¡blocking!

#7047 customizable prompt
  conda/_vendor/auxlib/type_coercion.py
  conda/activate.py
  conda/base/context.py
  tests/test_activate.py
Labels: Ready for Review, tag:shell

#7180 fix #7109 incorrect chown with sudo
  circle.yml
  conda/base/context.py
  conda/common/io.py
  conda/core/package_cache_data.py
  conda/exceptions.py
  conda/gateways/disk/__init__.py
  conda/gateways/disk/create.py
  conda/gateways/disk/update.py
  tests/base/test_context.py
Labels: Ready for Review

#7195 resolve #7194 change default value of max_shlvl to 0
  CONTRIBUTING.md
  appveyor.yml
  circle.yml
  conda/activate.py
  conda/base/context.py
  conda/cli/main_info.py
  conda/cli/main_init.py
  conda/core/initialize.py
  conda/exceptions.py
  conda/shell/Library/bin/conda.bat
  conda/shell/bin/activate
  conda/shell/bin/deactivate
  conda/shell/condacmd/conda-hook.bat
  conda/shell/condacmd/conda.bat
  conda/shell/condacmd/conda_activate.bat
  conda/shell/condacmd/conda_auto_activate.bat
  conda/shell/condacmd/conda_hook.bat
  conda/shell/etc/fish/conf.d/conda.fish
  conda/shell/etc/profile.d/conda.sh
  dev/start
  dev/start.bat
  dev/start.sh
  tests/cli/test_activate.py
  tests/core/test_initialize.py
  tests/test_activate.py
Labels: Ready for Review, deprecation-or-behavior-change

#7224 fix #7094 exit early for --dry-run with explicit and clone
  conda/misc.py
  tests/test_create.py
Labels: Ready for Review

#7226 activation refinement
  conda/core/initialize.py
  conda/exceptions.py
  conda/shell/conda.xsh
  conda/shell/condacmd/_conda_activate.bat
  conda/shell/condacmd/conda.bat
  conda/shell/condacmd/conda_auto_activate.bat
  conda/shell/condacmd/conda_hook.bat
  conda/shell/etc/fish/conf.d/conda.fish
  conda/shell/etc/profile.d/conda.csh
  conda/shell/etc/profile.d/conda.sh
  tests/core/test_initialize.py
Labels: Ready for Review
