Repository conda/conda, pull requests merged in 2019-12, with the labels that each got.

#9478 Typo in condarc key envs_dirs
  docs/source/user-guide/configuration/use-condarc.rst
Labels: cla-signed

#9483 Added Miniconda link to glossary
  docs/source/glossary.rst
Labels: cla-signed

#9465 Support Object configuration parameters
  conda/common/configuration.py
  tests/common/test_configuration.py
Labels: cla-signed

#9472 Don't check in pkgs for trash
  conda/gateways/disk/delete.py
Labels: cla-signed

#9492 Clarified channel priority
  docs/source/user-guide/tasks/manage-channels.rst
Labels: cla-signed

#9453 DLL loading verification in Activate an Env
  docs/source/user-guide/tasks/manage-environments.rst
  docs/source/user-guide/troubleshooting.rst
Labels: cla-signed

#9524 add -n base to the install anaconda-client suggestion
  conda_env/specs/binstar.py
Labels: cla-signed

#9485 remove setuptools from run_constrained in recipe
  recipe/meta.yaml
Labels: cla-signed

#9464 Fix #8243 incorrect chown call
  conda/gateways/disk/update.py
Labels: cla-signed

#9460 Fix for #9220 - exist with pip errorlevel if failed
  conda/utils.py
  tests/conda_env/test_cli.py
Labels: cla-signed

#9427 common.logic refactor/cleanup
  conda/common/_logic.py
  conda/common/logic.py
  conda/resolve.py
  tests/test_logic.py
Labels: cla-signed, source-contributor, tag-solver

#9525 add networking args to conda env create
  conda_env/cli/main_create.py
Labels: cla-signed

#9534 Installing with specific build number
  docs/source/user-guide/concepts/installing-with-conda.rst
Labels: cla-signed

#9533 Fix unit tests on ci setup
  circle.yml
Labels: cla-signed

#9537 fix overly greedy capture done by subprocess for conda run
  conda/cli/conda_argparse.py
  conda/cli/main_run.py
  conda/cli/python_api.py
  conda/exceptions.py
  conda/shell/etc/profile.d/conda.sh
  tests/test_create.py
Labels: cla-signed

#9538 Release notes 4.8.1
  docs/source/release-notes.rst
Labels: cla-signed

#9539 make frozendict JSON serializable
  conda/__init__.py
  conda/_vendor/frozendict.py
Labels: cla-signed

#7000 Fix #6996: change fish prompt only if changeps1 is true
  conda/shell/etc/fish/conf.d/conda.fish
Labels: tag-shell
