Repository conda/conda, pull requests merged in 2020-07, with the labels that each got.

#10042 docs: fix missing space in command typo
  docs/source/user-guide/install/rpm-debian.rst
Labels: cla-signed

#10051 Enable s390x support in cpuinfo
  conda/_vendor/cpuinfo.py
Labels: cla-signed

#10054 fixup the documentation for the --channel option
  conda/cli/conda_argparse.py
Labels: cla-signed

#10010 Fix failing codecov upload in CI test suite
  appveyor.yml
  circle.yml
Labels: cla-signed

#10069 Fix code page issue
  appveyor.yml
  conda/activate.py
  conda/models/enums.py
  conda/shell/condabin/_conda_activate.bat
Labels: cla-signed

#8727 JSON-format activation
  conda/activate.py
  conda/base/context.py
  conda/common/pkg_formats/python.py
  conda/gateways/disk/delete.py
  tests/test_activate.py
Labels: cla-signed, tag-conda_run

#10028 Fix #10027
  conda/cli/install.py
Labels: cla-signed

#10002 Update unix.py
  conda/common/_os/unix.py
Labels: cla-signed

#9938 Remove apt-get update from example travis file
  docs/source/user-guide/tasks/use-conda-with-travis-ci.rst
Labels: cla-signed

#10032 Add spinner to pip installer
  conda_env/installers/pip.py
Labels: cla-signed

#9909 Bug fix regarding issue #9893
  conda_env/cli/main_export.py
Labels: cla-signed

#9999 Update prefix_data.py
  conda/core/prefix_data.py
Labels: cla-signed

#9919 Allow retries for 500 error code.
  .cla-signers
  conda/gateways/connection/session.py
Labels: cla-signed

#10005 suppress spurious xonsh activation warnings
  conda/activate.py
  conda/shell/conda.xsh
  tests/test_activate.py
Labels: cla-signed

#10022 ENH: Compare environments
  conda/cli/conda_argparse.py
  conda/cli/main_compare.py
  tests/test_cli.py
  tests/test_create.py
Labels: cla-signed

#9902 audit yaml usage for safe_load vs round_trip_load
  conda.recipe/meta.yaml
  conda/_vendor/auxlib/configuration.py
  conda/cli/main_config.py
  conda/common/configuration.py
  conda/common/serialize.py
  conda_env/env.py
  conda_env/yaml.py
  tests/base/test_context.py
  tests/cli/test_config.py
  tests/common/test_configuration.py
  tests/common/test_yaml.py
  tests/conda_env/test_cli.py
  tests/conda_env/test_env.py
  tests/models/test_channel.py
  tests/test_create.py
  tests/test_utils.py
Labels: cla-signed

#10078 List CURL_CA_BUNDLE also
  conda/cli/main_info.py
  docs/source/user-guide/configuration/non-standard-certs.rst
Labels: cla-signed

#10086 Prevent `conda remove --all` from deleting non-environments
  conda/cli/main_remove.py
  tests/test_create.py
Labels: cla-signed

#9665 set errorlevel when 'conda run' exits (Resolves #9599)
  conda/cli/main.py
  tests/test_cli.py
Labels: cla-signed

#10090 Prevent `conda create -d -y` from destroying existing environments
  conda/cli/main_create.py
  tests/test_create.py
Labels: cla-signed

#10093 Fix some deprecation warnings for imports and regex: #10083
  conda/_vendor/auxlib/compat.py
  conda/common/path.py
  conda/core/subdir_data.py
  conda/gateways/disk/create.py
  conda/gateways/disk/link.py
  test_data/env_metadata/__init__.py
Labels: cla-signed

#10096 Fix windows path and header regexes
  conda/common/path.py
  conda/core/subdir_data.py
Labels: cla-signed

#9738 fix #9737 --json with inconsistent environment
  conda/core/solve.py
  tests/test_create.py
Labels: cla-signed

#10089 Clarify that Python is not by default included
  docs/source/user-guide/tasks/manage-environments.rst
Labels: cla-signed

#10108 Fix bug in python 2.7 64-bit platforms
  conda/common/_logic.py
Labels: cla-signed

#9649 Removed extra newline from conda env export
  conda_env/cli/main_export.py
Labels: cla-signed

#10115 Updated tqdm to 4.48.0, to fix leaked semaphore issue under Python 3.8
  conda/_vendor/tqdm/LICENSE
  conda/_vendor/tqdm/__init__.py
  conda/_vendor/tqdm/__main__.py
  conda/_vendor/tqdm/_main.py
  conda/_vendor/tqdm/_monitor.py
  conda/_vendor/tqdm/_tqdm.py
  conda/_vendor/tqdm/_utils.py
  conda/_vendor/tqdm/_version.py
  conda/_vendor/tqdm/cli.py
  conda/_vendor/tqdm/std.py
  conda/_vendor/tqdm/utils.py
Labels: cla-signed

#9889 replace listdir and glob with scandir
  appveyor.yml
  conda.recipe/meta.yaml
  conda/activate.py
  conda/cli/install.py
  conda/common/_os/linux.py
  conda/common/compat.py
  conda/common/configuration.py
  conda/common/pkg_formats/python.py
  conda/core/envs_manager.py
  conda/core/package_cache_data.py
  conda/core/prefix_data.py
  conda/gateways/anaconda_client.py
  conda/gateways/disk/delete.py
  conda/gateways/disk/read.py
  conda/misc.py
  tests/test_create.py
Labels: cla-signed

#9623 doc/custom channels: fix formatting and typo
  docs/source/user-guide/tasks/create-custom-channels.rst
Labels: cla-signed, tag-documentation

#9660 print help on incomplete command
  conda_env/cli/main_config.py
Labels: cla-signed
