Repository conda/conda, pull requests merged in 2021-11, with the labels that each got.

#11012 GitHub Action to build/upload conda packages on CI tests success
  .github/workflows/build-upload-pkgs.yaml
  conda.recipe/bld.bat
  conda.recipe/build.sh
  conda.recipe/conda_build_config.yaml
  conda.recipe/meta.yaml
  conda.recipe/run_test.bat
  conda.recipe/run_test.sh
Labels: cla-signed

#11018 Use xdoctest instead of doctest for better error handling.
  conda/cli/python_api.py
  setup.cfg
  tests/requirements.txt
Labels: cla-signed, type-documentation

#10933 Add architecture docs
  .gitignore
  .readthedocs.yml
  Makefile
  conda/cli/conda_argparse.py
  conda/cli/python_api.py
  docs/Makefile
  docs/requirements.txt
  docs/source/_ext/conda_umls.py
  docs/source/_static/css/custom.css
  docs/source/_static/js/panzoom.js
  docs/source/architecture.rst
  docs/source/commands.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/umls/container/channels.puml
  docs/source/umls/container/conda.puml
  docs/source/umls/context/context.puml
  docs/source/umls/includes/base.puml
  docs/source/umls/includes/rels.puml
  docs/source/umls/includes/style.puml
  docs/source/user-guide/index.rst
Labels: cla-signed, type-documentation

#11019 Remove conda-docs workflow in favor of using Read The Docs PR integration.
  .github/workflows/docs.yml
  Makefile
Labels: cla-signed

#11009 Pre-commit, darker, blacken-docs, flake8, pylint, bandit
  .pre-commit-config.yaml
  CONTRIBUTING.md
  pyproject.toml
  tests/requirements.txt
Labels: cla-signed

#10982 Add path ~/.config/conda/condarc into SEARCH_PATH to follow the XDG Base Directory Specification.
  conda/base/constants.py
  docs/source/user-guide/configuration/use-condarc.rst
Labels: cla-signed

#11026 Additional exclusions from pre-commit
  .cla-signers
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/speed_improvement.yml
  .pre-commit-config.yaml
  conda/shell/condabin/_conda_activate.bat
  conda/shell/condabin/conda-hook.ps1
  conda/shell/condabin/rename_tmp.bat
  docs/source/_static/css/custom.css
  docs/source/commands.rst
  docs/source/img/conda_logo.svg
  docs/source/user-guide/concepts/conda-performance.rst
  docs/source/user-guide/concepts/environments.rst
  docs/source/user-guide/concepts/index.rst
  docs/source/user-guide/concepts/installing-with-conda.rst
  docs/source/user-guide/concepts/packages.rst
  docs/source/user-guide/concepts/pkg-specs.rst
  docs/source/user-guide/configuration/enable-tab-completion.rst
  docs/source/user-guide/configuration/free-channel.rst
  docs/source/user-guide/configuration/pip-interoperability.rst
  docs/source/user-guide/configuration/use-condarc.rst
  docs/source/user-guide/getting-started.rst
  docs/source/user-guide/install/download.rst
  docs/source/user-guide/install/linux.rst
  docs/source/user-guide/install/rpm-debian.rst
  docs/source/user-guide/install/windows.rst
  docs/source/user-guide/tasks/create-custom-channels.rst
  docs/source/user-guide/tasks/manage-channels.rst
  docs/source/user-guide/tasks/manage-conda.rst
  docs/source/user-guide/tasks/manage-environments.rst
  docs/source/user-guide/tasks/manage-pkgs.rst
  docs/source/user-guide/tasks/use-conda-with-travis-ci.rst
  docs/source/user-guide/troubleshooting.rst
  tests/base/test_context.py
  tests/common/test_configuration.py
  tests/common/test_io.py
  tests/conda_env/support/empty_env.yml
  tests/conda_env/support/env_with_dependencies.yml
  tests/conda_env/support/notebook.ipynb
  tests/conda_env/test_cli.py
  tests/data/_conda_test_env_activated_when_post_link_executed_recipe/meta.yaml
  tests/data/index2.json
  tests/data/index4.json
  tests/data/index5.json
  tests/integration/proxy/.gitignore
  tests/integration/proxy/proxy-test.sh
  tests/models/test_channel.py
  tests/models/test_prefix_graph.py
  tests/test_export.py
  tests/test_install.py
  tests/test_utils.py
Labels: cla-signed

#11027 Delete lint.yml
  .github/workflows/lint.yml
Labels: cla-signed

#11028 Update templates/workflows to use new label formats
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/speed_improvement.yml
  .github/workflows/stale.yml
Labels: type::task, cla-signed

#11036 Catch UnicodeDecodeError when parsing conda-meta files
  .pre-commit-config.yaml
  conda/core/prefix_data.py
  tests/core/test_prefix_data.py
  tests/data/corrupt/json/conda-meta/corrupt-1.2.3-hashhash.json
  tests/data/corrupt/unicode/conda-meta/corrupt-1.2.3-hashhash.json
Labels: cla-signed

#11039 Add rever for release management
  .authors.yml
  .gitignore
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  CONTRIBUTING.md
  news/TEMPLATE
  rever.xsh
Labels: cla-signed

#11029 Automate moving to/from boards
  .github/workflows/boards.yml
Labels: type::task, cla-signed

#11044 Fix PowerShellActivator unsetting env
  conda/activate.py
  tests/test_activate.py
Labels: cla-signed

#11040 Enable one-click gitpod setup for Linux development (WIP)
  .devcontainer.json
  .gitpod.yml
  README.rst
  ci/scripts/linux/setup.sh
  dev/docker.bashrc
Labels: cla-signed

#10696 Remove extra evals in fish shell
  conda/shell/etc/fish/conf.d/conda.fish
Labels: cli, cla-signed, cli::fish

#10772 Support running conda with PyPy on windows
  conda/gateways/disk/link.py
Labels: cla-signed

#9789 Set errno on NotWritableError
  conda/exceptions.py
Labels: cla-signed

#11045 change bare `conda update` error message
  conda/cli/install.py
Labels: cla-signed

#11041 Add developer guide section to docs
  .github/workflows/ci-images.yml
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Dockerfile
  dev/linux/bashrc.sh
  dev/linux/integration.sh
  dev/linux/setup.sh
  dev/linux/unit.sh
  dev/windows/integration.bat
  dev/windows/setup.bat
  dev/windows/unit.bat
  docker-compose.yml
  docs/source/dev-guide/contributing.md
  docs/source/dev-guide/index.rst
  docs/source/index.rst
Labels: cla-signed, type::documentation

#11048 Use conda search instead of deprecated info subcommand in docs.
  docs/source/user-guide/tasks/manage-pkgs.rst
  docs/source/user-guide/troubleshooting.rst
Labels: cla-signed, type::documentation

#11049 Add news items for 4.11.
  news/gh-10436-powershell-activator
  news/gh-10628-interpolate-channel_alias
  news/gh-10696-fish-eval
  news/gh-10772-pypy-windows
  news/gh-10795-conda-ci
  news/gh-10799-conda-path-rhel
  news/gh-10815-fix-pip-advanced-docs
  news/gh-10831-stale-github-action
  news/gh-10832-lock-threads-github-action
  news/gh-10864-ci-refactor
  news/gh-10878-github-issue-forms
  news/gh-10896-indent-fish
  news/gh-10898-docs-cleanup
  news/gh-10905-envvars
  news/gh-10933-architecture-docs
  news/gh-10950-permissionerror
  news/gh-10952-config-sequences
  news/gh-10970-python310
  news/gh-10982-XDG_CONFIG_HOME
  news/gh-11009-styles
  news/gh-11012-conda-canary
  news/gh-11029-triaging
  news/gh-11036-unicode-conda-meta
  news/gh-11039-rever
  news/gh-11040-gitpod-codespaces
  news/gh-11041-dev-guide
  news/gh-11045-update-help
  news/gh-9789-set-errno
Labels: cla-signed, type::documentation

#11052 Use the appropriate token for GHA
  .github/workflows/boards.yml
Labels: cla-signed

#10886 Adapt behavioural tests in `tests.test_resolve` for multiple solvers
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/exceptions.py
  tests/helpers.py
  tests/test_solvers.py
Labels: cla-signed, type::poc

#10652 Make sure that `conda env update -f` sets env vars from the referenced yaml file
  conda_env/cli/main_update.py
  tests/conda_env/support/example/environment_pinned.yml
  tests/conda_env/support/example/environment_pinned_updated.yml
  tests/conda_env/test_create.py
Labels: cla-signed

#10983 [Mamba POC] Bring in more conda logic
  conda/common/url.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/exceptions.py
  dev/linux/experimental-resolver.sh
  dev/linux/integration.sh
  dev/linux/unit.sh
  dev/windows/experimental-resolver.bat
  dev/windows/unit.bat
  tests/cli/test_cli_install.py
  tests/core/test_solve.py
  tests/data/index4.json
  tests/helpers.py
  tests/test_create.py
  tests/test_solvers.py
Labels: cla-signed, type::poc

#11070 Fix apparent typo: memoizeproperty -> memoizedproperty
  conda/auxlib/decorators.py
Labels: cla-signed

#11068 Automatically handle milestoned/demilestoned/commented issues
  .github/workflows/boards.yml
Labels: cla-signed
