Repository conda/conda, pull requests merged in 2021-09, with the labels that each got.

#10765 Add Windows versions to system requirements
  docs/source/user-guide/install/index.rst
Labels: cla-signed, type-documentation

#10893 [Mamba POC] - Rework `to_txn` usage to fix virtual packages KeyErrors
  conda/core/solve.py
Labels: cla-signed, type-poc

#10920 Added the speed form, deleted old markdown
  .github/ISSUE_TEMPLATE/Speed_complaint.md
  .github/ISSUE_TEMPLATE/speed_improvement.yml
Labels: cla-signed

#10909 Removed the old feat req markdown. Replaced with new yml format for github forms
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: cla-signed

#10906 [Mamba POC] Fix local channels handling
  conda/core/solve.py
Labels: cla-signed, type-poc

#10904 [Mamba POC] Deal with JSON output errors
  conda/core/solve.py
Labels: cla-signed, type-poc

#10900 [Mamba POC] Implement early exit strategies
  conda/common/url.py
  conda/core/solve.py
  tests/core/test_solve.py
  tests/test_create.py
Labels: cla-signed, type-poc

#10894 [Mamba POC] - Rework Solver API to rely on `Solver.solve_final_state`
  conda/common/url.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/exceptions.py
  tests/core/test_solve.py
  tests/helpers.py
  tests/test_create.py
Labels: cla-signed, type-poc

#10898 Contributing and CLA docs cleanup
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: cla-signed

#10899 Stop pointing to the anaconda issues tracker.
  conda/core/path_actions.py
Labels: cla-signed

#10905 fix bug in setting environment variables
  conda_env/cli/main_vars.py
  tests/conda_env/test_cli.py
Labels: type-bug, tag-conda_env, cla-signed

#10929 [Mamba POC] Enable windows tests
  .github/workflows/ci.yml
  ci/scripts/windows/experimental-resolver.bat
  ci/scripts/windows/setup.bat
Labels: cla-signed, type-poc

#10936 [Mamba POC] Fix YAML parsing in `test_create_dry_run_yaml`
  conda/core/solve.py
  tests/conda_env/test_cli.py
Labels: cla-signed, type-poc

#10937 [Mamba POC] Handle UpdateModifier.UPDATE_DEPS correctly (all graph, not just leaves)
  conda/base/context.py
  conda/core/solve.py
Labels: cla-signed, type-poc

#10943 [Mamba POC] Research `conflicting requests` errors: --update-deps
  conda/core/solve.py
Labels: cla-signed, type-poc

#10948 Force remove miniconda in dev/start
  dev/start
Labels: cla-signed
