Repository conda/conda, pull requests merged in 2021-06, with the labels that each got.

#10516 Don't create an unused s3 client at import time.
  conda/gateways/connection/adapters/s3.py
Labels: cla-signed

#10329 Update docs
  docs/source/user-guide/concepts/channels.rst
  docs/source/user-guide/concepts/installing-with-conda.rst
  docs/source/user-guide/concepts/pkg-specs.rst
  docs/source/user-guide/getting-started.rst
  docs/source/user-guide/install/download.rst
  docs/source/user-guide/tasks/manage-channels.rst
  docs/source/user-guide/tasks/manage-python.rst
Labels: cla-signed, type-documentation

#10712 fix typo
  docs/source/user-guide/tasks/manage-python.rst
Labels: cla-signed

#10692 Don't load binstar_client until needed. Part 2.
  conda_env/specs/binstar.py
Labels: cla-signed, tag-performance

#10715 Update release notes.
  docs/source/release-notes.rst
Labels: cla-signed, tag-documentation, type-documentation

#10721 bump vendored tqdm version
  conda/_vendor/tqdm/__init__.py
  conda/_vendor/tqdm/__main__.py
  conda/_vendor/tqdm/_main.py
  conda/_vendor/tqdm/_monitor.py
  conda/_vendor/tqdm/_tqdm.py
  conda/_vendor/tqdm/_utils.py
  conda/_vendor/tqdm/_version.py
  conda/_vendor/tqdm/asyncio.py
  conda/_vendor/tqdm/auto.py
  conda/_vendor/tqdm/cli.py
  conda/_vendor/tqdm/contrib/__init__.py
  conda/_vendor/tqdm/contrib/concurrent.py
  conda/_vendor/tqdm/contrib/itertools.py
  conda/_vendor/tqdm/std.py
  conda/_vendor/tqdm/utils.py
  conda/_vendor/tqdm/version.py
Labels: cla-signed

#10728 maint: update macos install guide
  docs/source/user-guide/install/macos.rst
Labels: cla-signed, s-2, tag-documentation, type-documentation

#10624 Fix changeps1 implementation for Powershell
  conda/activate.py
  conda/shell/condabin/Conda.psm1
  conda/shell/condabin/conda-hook.ps1
Labels: cla-signed, tag-shell-powershell, tag-windows

#10631 fix some issues in conda.sh (injected in .bashrc)
  conda/shell/etc/profile.d/conda.sh
Labels: cla-signed, tag-shell-posix

#9998 Fix log level in conda/core/prefix_data.py
  conda/core/prefix_data.py
Labels: cla-signed, type-techdebt

#10735 Fix channel args cli
  conda/base/context.py
  conda/cli/main_info.py
  tests/base/test_context.py
Labels: cla-signed

#10701 Allow profile.d/conda.sh to pass if set -eu on
  conda/shell/etc/profile.d/conda.sh
Labels: cla-signed, tag-shell, tag-shell-posix

#10744 Update manage-python.rst
  docs/source/user-guide/tasks/manage-python.rst
Labels: cla-signed

#10745 Merge release notes and changelog.
  CHANGELOG.md
  docs/source/conf.py
  docs/source/release-notes.md
  docs/source/release-notes.rst
  docs/source/user-guide/tasks/manage-python.rst
  docs/source/user-guide/troubleshooting.rst
  utils/environment.yml
  utils/requirements-docs.txt
  utils/requirements.txt
Labels: cla-signed, tag-documentation, type-documentation

#10749 4.10.2 changelog
  CHANGELOG.md
Labels: cla-signed

#10752 ReadTheDocs config and dependency cleanup
  .readthedocs.yml
  Makefile
  ci/build_docs.sh
  conda/cli/python_api.py
  docs/requirements.txt
  utils/environment.yml
  utils/functions.sh
  utils/requirements-docs.txt
  utils/requirements-test.txt
  utils/requirements.txt
  utils/setup-testing.py
Labels: cla-signed

#10759 Revert S3 client initialization added in #10516
  CHANGELOG.md
  conda/gateways/connection/adapters/s3.py
Labels: cla-signed
