Repository conda/conda, pull requests merged in 2022-08, with the labels that each got.

#11671 Always mention channel in the outdated conda messages
  conda/core/solve.py
  news/11671-channel-update
Labels: cla-signed

#11649 Use `**kwargs` instead of `OrderedDict` for `_Activator.get_export_unset_vars`
  conda/activate.py
  news/11649-refactor-get_export_unset_vars
  tests/test_activate.py
Labels: source::anaconda, cla-signed, sprint

#11678 Deprecate unused `conda.another_to_unicode`
  conda/__init__.py
  news/11678-pendingdeprecation-another_to_unicode
Labels: cla-signed, sprint

#11679 Fix `log.debug` `TypeError` in `conda.core.package_cache_data`
  conda/core/package_cache_data.py
  news/11679-fix-typeerror.md
Labels: cla-signed

#11681 Use a PEP 440 compatible version for canary recipe
  conda.recipe/meta.yaml
Labels: cla-signed, sprint

#11668 Release 4.14.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/11462-cep-6-channel-notices
  news/11483-update-environment-variables-expansion-list-to-include-channel_alias
  news/11490-deprecate-conda.cli.common.ensure_name_or_prefix
  news/11496-new-rename-command
  news/11542-conda-crashes-on-empty-environment
  news/11542-documentation-pip
  news/11544-convert-readme-markdown
  news/11564-ssl-errors
  news/11570-rename-master-to-main
  news/11571-pendingdeprecation-conda.lock
  news/11572-remove-lgtm
  news/11573-remove-is_ipv6_address_win_py27
  news/11594-pendingdeprecation-get_prefix
  news/11595-pendingdeprecation-conda_env.cli.common.stdout_json
  news/11596-pendingdeprecation-conda_env.cli.common.find_prefix_name
  news/11597-pendingdeprecation-conda.auxlib.decorators.memoize
  news/11601-mention-invalid-name-in-error-message
  news/11625-correct-conda-help-err-msg
  news/11626-cuda-wsl2
  news/11647-allowlist_channels
  news/11649-refactor-get_export_unset_vars
  news/11658-add-fips-md5-support
  news/11671-channel-update
  news/11678-pendingdeprecation-another_to_unicode
  news/11679-fix-typeerror.md
  news/8135-conda-init-undocumented-arguments
  news/9396-outdated-examples-section-in-help-for-conda-env-create
Labels: source::anaconda, cla-signed

#11589 Add cytoolz as dependency
  conda.recipe/meta.yaml
  conda/_vendor/toolz/LICENSE.txt
  conda/_vendor/toolz/__init__.py
  conda/_vendor/toolz/compatibility.py
  conda/_vendor/toolz/dicttoolz.py
  conda/_vendor/toolz/itertoolz.py
  conda/_vendor/toolz/recipes.py
  conda/_vendor/toolz/utils.py
  conda/_vendor/vendor.txt
  conda/activate.py
  conda/base/context.py
  conda/cli/main_config.py
  conda/common/configuration.py
  conda/common/path.py
  conda/common/pkg_formats/python.py
  conda/core/index.py
  conda/core/link.py
  conda/core/package_cache_data.py
  conda/core/path_actions.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/exceptions.py
  conda/history.py
  conda/models/channel.py
  conda/models/match_spec.py
  conda/models/version.py
  conda/plan.py
  conda/resolve.py
  conda_env/env.py
  news/11333-replace-toolz-dependency-with-cytoolz
  tests/base/test_context.py
  tests/core/test_path_actions.py
  tests/test_activate.py
  tests/test_create.py
  tools/vendoring/patches/toolz.patch
Labels: source::anaconda, cla-signed

#11688 Adding `conda_env` to coverage reports
  .codecov.yml
Labels: cla-signed

#11690 Modify `ExceptionHandler.write_out` to use `*args`
  conda/exceptions.py
Labels: cla-signed

#11692 Move `ExceptionHandler._calculate_ask_do_upload`'s `isatty` value into a cached property
  conda/exceptions.py
Labels: cla-signed

#11691 Simplify `ExceptionHandler._calculate_ask_do_upload ` logic
  conda/common/io.py
  conda/exceptions.py
Labels: cla-signed

#11697 Add sphinx-sitemap to docs.
  docs/requirements.txt
  docs/source/conf.py
  docs/source/robots.txt
Labels: cla-signed, sprint

#11705 Finish removing `conda._vendor.urllib3`
  conda/_vendor/vendor.txt
  pyproject.toml
  tools/vendoring/patches/urllib3.exceptions.patch
  tools/vendoring/patches/urllib3.patch
  tools/vendoring/patches/urllib3.util.patch
Labels: cla-signed, sprint

#11704 Revert dropping `conda._vendor.toolz`
  conda/_vendor/toolz/LICENSE.txt
  conda/_vendor/toolz/__init__.py
  conda/_vendor/toolz/compatibility.py
  conda/_vendor/toolz/dicttoolz.py
  conda/_vendor/toolz/itertoolz.py
  conda/_vendor/toolz/recipes.py
  conda/_vendor/toolz/utils.py
  conda/_vendor/vendor.txt
  news/11333-replace-toolz-dependency-with-cytoolz
  tools/vendoring/patches/toolz.patch
Labels: cla-signed, sprint

#11700 Require `toolz` & soften `cytoolz` dependency
  conda.recipe/meta.yaml
  news/11333-replace-toolz-dependency-with-cytoolz
  recipe/meta.yaml
  tests/requirements.txt
Labels: cla-signed

#11646 Refactor content trust into submodule
  conda/base/constants.py
  conda/core/link.py
  conda/core/subdir_data.py
  conda/models/enums.py
  conda/models/records.py
  conda/trust/__init__.py
  conda/trust/constants.py
  conda/trust/signature_verification.py
Labels: source::anaconda, cla-signed, sprint

#11707 normalize unused lazy import
  conda/common/serialize.py
Labels: cla-signed

#11709 Add `conda._vendor.toolz` fallback for `tlz`
  conda/activate.py
  conda/base/context.py
  conda/cli/main_config.py
  conda/common/configuration.py
  conda/common/path.py
  conda/common/pkg_formats/python.py
  conda/core/index.py
  conda/core/link.py
  conda/core/package_cache_data.py
  conda/core/path_actions.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/exceptions.py
  conda/history.py
  conda/models/channel.py
  conda/models/match_spec.py
  conda/models/version.py
  conda/plan.py
  conda/resolve.py
Labels: cla-signed

#11666 Resolve prefix injection
  conda/activate.py
  conda/shell/condabin/Conda.psm1
  conda/shell/condabin/_conda_activate.bat
  conda/shell/condabin/conda.bat
  conda/shell/etc/profile.d/conda.csh
  conda/shell/etc/profile.d/conda.sh
  dev/windows/setup.bat
  tests/test_activate.py
Labels: source::anaconda, cla-signed

#11722 Remove CSH prefix injection
  conda/shell/etc/profile.d/conda.csh
Labels: cla-signed, sprint

#11720 Debugging borked builds
  conda.recipe/run_test.sh
Labels: cla-signed

#11736 add dash to license per SPDX standards
  conda.recipe/meta.yaml
Labels: cla-signed

#11754 Fix failing stacking tests
  dev/linux/integration.sh
Labels: cla-signed, sprint

#11753 Change Debian Image from `buster-slim` to `stable-slim` on Dockerfile
  Dockerfile
Labels: source::anaconda, cla-signed, sprint, type::testing

#11746 Modify `ExceptionHandler.write_out` to Properly Show Errors
  conda/exceptions.py
  news/11746-modify-write-out
Labels: cla-signed

#11752 update dev/start for arm64
  dev/start
  news/11751-arm64-dev-support
Labels: cla-signed

#11762 Formatting `rename` Command Examples to Have Proper Line Spacing
  conda/cli/conda_argparse.py
Labels: source::anaconda, cla-signed, type::documentation, sprint

#11761 Use `canary-release@v22.8.0` to resolve broken canary build issue
  .github/workflows/builds-canary.yaml
  .github/workflows/builds-review.yaml
  news/11761-use-canary-releasev22.8.0
Labels: cla-signed, sprint

#11766 remove toolz.drop()
  conda/activate.py
  conda/models/channel.py
Labels: cla-signed

#11712 Added conda capitalization standards to CONTRIBUTING.md.
  CONTRIBUTING.md
  news/11711-add-conda-capitalization-standards
Labels: cla-signed

#11773 Remove old conda recipe
  recipe/bld.bat
  recipe/build.sh
  recipe/meta.yaml
Labels: cla-signed

#11435 Add Plugin Mechanism
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/main.py
  conda/exceptions.py
  conda/plugins/__init__.py
  docs/requirements.txt
  docs/source/conf.py
  docs/source/dev-guide/index.rst
  docs/source/dev-guide/plugin-api/index.rst
  docs/source/dev-guide/plugin-api/subcommands.rst
  news/11435-plugins-mechanism
  tests/cli/test_conda_argparse.py
  tests/conda_env/test_cli.py
  tests/plugins/conftest.py
  tests/plugins/test_subcommands.py
  tests/requirements.txt
Labels: source::anaconda, cla-signed, plugins
