Repository conda/conda, pull requests merged in 2022-11, with the labels that each got.

#11854 Implement Virtual Packages Plugins
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/common/cuda.py
  conda/common/decorators.py
  conda/core/index.py
  conda/models/plugins.py
  conda/plugins/__init__.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/plugins/virtual_packages/__init__.py
  conda/plugins/virtual_packages/archspec.py
  conda/plugins/virtual_packages/cuda.py
  conda/plugins/virtual_packages/linux.py
  conda/plugins/virtual_packages/osx.py
  conda/plugins/virtual_packages/windows.py
  docs/source/commands.rst
  docs/source/conf.py
  docs/source/dev-guide/index.rst
  docs/source/dev-guide/plugin-api/subcommands.rst
  docs/source/dev-guide/plugins/index.rst
  docs/source/dev-guide/plugins/subcommands.rst
  docs/source/dev-guide/plugins/virtual_packages.rst
  news/11854-virtual-packages-plugins
  tests/base/test_context.py
  tests/conftest.py
  tests/core/test_index.py
  tests/core/test_solve.py
  tests/plugins/conftest.py
  tests/plugins/test_subcommands.py
  tests/plugins/test_virtual_packages.py
  tests/test_activate.py
  tests/test_create.py
  tests/test_priority.py
Labels: source::anaconda, cla-signed, plugins, sprint

#12044 Fixes a bug with the current documentation
  docs/requirements.txt
Labels: cla-signed

#12014 Fix crashes in MatchSpec, VersionSpec parsing
  conda/models/match_spec.py
  conda/models/version.py
  news/11999-fix-fuzzing-crashes
  tests/models/test_match_spec.py
  tests/models/test_version.py
Labels: type::bug, cla-signed, sprint

#12042 Use GNU tar to successfully restore Windows github actions cache
  .github/workflows/tests.yml
  dev/linux/integration.sh
  dev/linux/unit.sh
  dev/macos/setup.sh
Labels: cla-signed

#12052 Update token name to be more specific.
  .github/workflows/tests.yml
Labels: cla-signed

#12056 handle BaseException in package_cache_data for expedient CTRL-C handling
  conda/core/package_cache_data.py
Labels: cla-signed, sprint

#12054 reformat subdir_data.py with no additional changes
  conda/core/subdir_data.py
Labels: cla-signed

#12061 Update Docstring in Hookspec Module
  conda/plugins/hookspec.py
Labels: source::anaconda, cla-signed, sprint

#12024 tests: add local http server
  tests/conda_env/__init__.py
  tests/conda_env/support/example/environment_pinned.yml
  tests/conda_env/support/example/environment_pinned_updated.yml
  tests/conda_env/test_create.py
  tests/conftest.py
  tests/http_test_server.py
  tests/test_create.py
Labels: cla-signed

#12077 set pytest --basetemp
  dev/linux/integration.sh
  dev/linux/unit.sh
Labels: cla-signed

#12058 Move `conda.models.plugins` to `conda.plugins.types`
  conda/plugins/__init__.py
  conda/plugins/hookspec.py
  conda/plugins/types.py
  conda/plugins/virtual_packages/archspec.py
  conda/plugins/virtual_packages/cuda.py
  conda/plugins/virtual_packages/linux.py
  conda/plugins/virtual_packages/osx.py
  conda/plugins/virtual_packages/windows.py
  docs/source/dev-guide/plugins/subcommands.rst
  docs/source/dev-guide/plugins/virtual_packages.rst
  tests/plugins/test_subcommands.py
  tests/plugins/test_virtual_packages.py
Labels: cla-signed, plugins, type::poc, sprint

#12060 Implement `PluginManager.load_plugins`
  conda/plugins/manager.py
  conda/plugins/virtual_packages/__init__.py
  tests/plugins/conftest.py
Labels: cla-signed, plugins, type::poc, sprint

#11993 Add solver plugin hook
  conda/base/constants.py
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/main_config.py
  conda/core/index.py
  conda/core/solve.py
  conda/plugins/__init__.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/plugins/solvers.py
  conda/plugins/types.py
  conda_env/cli/main_remove.py
  conda_env/cli/main_update.py
  docs/source/dev-guide/plugins/index.rst
  docs/source/dev-guide/plugins/solvers.rst
  news/11993-implement-solver-pluginhook
  tests/cli/test_main_clean.py
  tests/plugins/conftest.py
  tests/plugins/test_solvers.py
  tests/plugins/test_subcommands.py
  tests/plugins/test_virtual_packages.py
Labels: cla-signed, plugins, sprint

#12062 Prevent [name=...] from overwriting name specified outside of brackets
  conda/models/match_spec.py
  news/12062-fix-name-overwrite
  tests/models/test_match_spec.py
Labels: type::bug, cla-signed, sprint

#12093 Move `conda.core.solve._get_solver_class` to `CondaPluginManager.get_solver_backend`
  conda/api.py
  conda/base/context.py
  conda/cli/install.py
  conda/cli/main_remove.py
  conda/core/solve.py
  conda/plan.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/testing/helpers.py
  conda_env/installers/conda.py
  docs/source/conf.py
  docs/source/dev-guide/plugins/index.rst
  docs/source/dev-guide/plugins/manager.rst
  docs/source/dev-guide/plugins/solvers.rst
  tests/core/test_solve.py
  tests/models/test_prefix_graph.py
  tests/plugins/test_solvers.py
  tests/test_exceptions.py
  tests/test_info.py
Labels: cla-signed, plugins, sprint

#12041 Refactor deep dives a little for more nesting.
  .gitignore
  docs/source/_ext/conda_umls.py
  docs/source/dev-guide/architecture.rst
  docs/source/dev-guide/deep-dives/activation.md
  docs/source/dev-guide/deep-dives/context.md
  docs/source/dev-guide/deep-dives/index.md
  docs/source/dev-guide/deep-dives/install.md
  docs/source/dev-guide/deep-dives/solvers.md
  docs/source/dev-guide/index.rst
  docs/source/dev-guide/specs/index.md
  docs/source/dev-guide/specs/solver-state.md
  docs/source/dev-guide/umls/container/channels.puml
  docs/source/dev-guide/umls/container/conda.puml
  docs/source/dev-guide/umls/context/context.puml
  docs/source/dev-guide/umls/includes/base.puml
  docs/source/dev-guide/umls/includes/rels.puml
  docs/source/dev-guide/umls/includes/style.puml
  docs/source/dev-guide/writing-tests/index.rst
Labels: cla-signed

#12101 Deprecate private conda env
  conda/base/context.py
  conda/cli/main_info.py
  conda/exports.py
Labels: cla-signed

#12088 Add More Plugins-Related Info to Conda Documentation
  docs/source/glossary.rst
  docs/source/user-guide/concepts/conda-plugins.rst
  docs/source/user-guide/concepts/index.rst
  docs/source/user-guide/tasks/manage-virtual.rst
Labels: source::anaconda, cla-signed, type::documentation, plugins, sprint

#12104 Don’t instantiate the solver backend for getting the user-agent.
  conda/base/context.py
  tests/plugins/test_solvers.py
Labels: cla-signed

#12108 news item for #11608 parallel downloads
  news/11608-parallel-package-download
Labels: sprint

#12043 Make sure conda does not use polyglot shebangs
  conda/core/initialize.py
  conda/core/portability.py
  news/12043-fix-shebang-ps1
  recipe/build.sh
  recipe/run_test.sh
  tests/core/test_path_actions.py
  tests/test_activate.py
Labels: cla-signed, sprint

#12115 Set env var triggering the isolated build mode added in conda-build 3.23.0
  .github/workflows/builds-review.yaml
  .github/workflows/tests.yml
  recipe/build.sh
  recipe/run_test.bat
  recipe/run_test.sh
Labels: cla-signed

#12120 Minor reformats suggested by `refurb`
  conda/__init__.py
  conda/auxlib/collection.py
  conda/auxlib/decorators.py
  conda/auxlib/entity.py
  conda/base/context.py
  conda/cli/common.py
  conda/cli/install.py
  conda/cli/main_config.py
  conda/cli/main_info.py
  conda/cli/python_api.py
  conda/common/configuration.py
  conda/common/pkg_formats/python.py
  conda/core/index.py
  conda/core/link.py
  conda/core/solve.py
  conda/gateways/anaconda_client.py
  conda/gateways/connection/adapters/ftp.py
  conda/gateways/subprocess.py
  conda/history.py
  conda/models/match_spec.py
  conda/notices/types.py
  conda/plan.py
  conda/resolve.py
  conda/testing/integration.py
  conda/testing/notices/helpers.py
  conda_env/cli/common.py
  conda_env/env.py
  tests/base/test_context.py
  tests/common/pkg_formats/test_python.py
  tests/models/test_channel.py
  tests/models/test_match_spec.py
  tests/models/test_version.py
  tests/test_activate.py
  tests/test_create.py
  tests/test_info.py
  tests/test_install.py
  tests/test_logic.py
Labels: cla-signed

#12127 Release 22.11.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/10665-add-env-variable
  news/11300-improve-cli-warning-conda-update
  news/11374-check-conda-exe-before-use
  news/11432-add-deprecation-warning-for-tqdm
  news/11435-plugins-mechanism
  news/11591-readable-error-message-if-packagecacherecords-missing
  news/11608-parallel-package-download
  news/11757-conda-cheatsheet-needs-updated-for-v4140
  news/11818-conda-hang
  news/11839-document-bashrc-bashprofile
  news/11851-devenv-mach-arch
  news/11854-virtual-packages-plugins
  news/11868-require-ruamel-yaml
  news/11889-remove-experimental-label
  news/11909-pyupgrade
  news/11944-update-metadata_signature_status-default
  news/11979-remove-vendored-six
  news/11993-implement-solver-pluginhook
  news/11999-fix-fuzzing-crashes
  news/12016-stop-using-toolz.functoolz.excepts
  news/12020-stop-using-toolz.itertoolz.concatv
  news/12040-update-canary-builds
  news/12043-fix-shebang-ps1
  news/12062-fix-name-overwrite
  news/7469-docs-describes-non-existent-option
  news/9782-broken-url-in-conda-documentation
Labels: cla-signed

#12132 Fix badges.
  README.md
Labels: cla-signed
