Repository conda/conda, pull requests merged in 2022-09, with the labels that each got.

#11778 Add `win-arm64` as a recognized platform
  conda/base/constants.py
  conda/models/enums.py
  news/11778-add-win-arm64
Labels: cla-signed

#11545 Change `conda-content-trust` from pre-solve to post-solve
  conda/core/link.py
  conda/core/subdir_data.py
  conda/models/records.py
  conda/trust/signature_verification.py
  news/11545-move-content-trust-into-submodule
Labels: source::anaconda, cla-signed

#11774 Rename `conda.recipe` to `recipe`
  news/11774-rename-conda.recipe
  recipe/bld.bat
  recipe/build.sh
  recipe/conda_build_config.yaml
  recipe/meta.yaml
  recipe/run_test.bat
  recipe/run_test.sh
Labels: cla-signed

#11708 Updated conda CLI help to be better for users.
  conda/cli/conda_argparse.py
Labels: cla-signed

#11734 Fix pypy win
  conda/gateways/disk/link.py
Labels: cla-signed

#11803 Fixes an issue that we are having with carnary builds
  recipe/run_test.sh
Labels: cla-signed

#11816 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla-signed

#11844 Release 22.9.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/11333-replace-toolz-dependency-with-cytoolz
  news/11676-prefix-spaces
  news/11711-add-conda-capitalization-standards
  news/11746-modify-write-out
  news/11751-arm64-dev-support
  news/11761-use-canary-releasev22.8.0
  news/11774-rename-conda.recipe
  news/11778-add-win-arm64
Labels: cla-signed

#11851 Expose --mach and --arch to devenv script
  dev/start
  news/11851-devenv-mach-arch
Labels: cla-signed, sprint

#11868 Require `ruamel.yaml`
  news/11868-require-ruamel-yaml
  recipe/meta.yaml
  setup.py
  tests/requirements.txt
Labels: cla-signed, sprint

#11842 Update flask version in conda_env/support
  tests/conda_env/support/requirements.txt
Labels: cla-signed

#11870 Minute Grammatical Changes made in Conda Commands Docs
  docs/source/user-guide/concepts/conda-commands.rst
Labels: cla-signed

#11866 Removed allow_other_channels from conda docs.
  docs/source/user-guide/configuration/admin-multi-user-install.rst
  docs/source/user-guide/configuration/use-condarc.rst
  news/7469-docs-describes-non-existent-option
Labels: cla-signed

#11837 Use maintained `ruamel.yaml`
  conda/base/constants.py
  conda/common/configuration.py
  conda/common/serialize.py
  conda_env/env.py
  news/11868-require-ruamel-yaml
  recipe/meta.yaml
  setup.py
  tests/conda_env/test_cli.py
  tests/requirements.txt
Labels: cla-signed

#11881 document conda-build: pkg_format: 2
  docs/source/user-guide/configuration/use-condarc.rst
Labels: cla-signed

#11892 Update `feature/plugins` Feature Branch
  .authors.yml
  .github/workflows/builds-canary.yaml
  .github/workflows/builds-review.yaml
  .mailmap
  .pre-commit-config.yaml
  AUTHORS.md
  CHANGELOG.md
  CONTRIBUTING.md
  RELEASE.md
  conda/base/constants.py
  conda/cli/conda_argparse.py
  conda/common/configuration.py
  conda/common/serialize.py
  conda/gateways/disk/link.py
  conda/models/enums.py
  conda_env/env.py
  dev/start
  docs/source/user-guide/concepts/conda-commands.rst
  docs/source/user-guide/configuration/admin-multi-user-install.rst
  docs/source/user-guide/configuration/use-condarc.rst
  news/11333-replace-toolz-dependency-with-cytoolz
  news/11676-prefix-spaces
  news/11746-modify-write-out
  news/11751-arm64-dev-support
  news/11851-devenv-mach-arch
  news/11868-require-ruamel-yaml
  news/7469-docs-describes-non-existent-option
  recipe/bld.bat
  recipe/build.sh
  recipe/conda_build_config.yaml
  recipe/meta.yaml
  recipe/run_test.bat
  recipe/run_test.sh
  rever.xsh
  setup.py
  tests/conda_env/support/requirements.txt
  tests/conda_env/test_cli.py
  tests/requirements.txt
Labels: cla-signed

#11862 Flatten script building for `conda init --dev`
  conda/core/initialize.py
Labels: type::tech-debt, cla-signed, sprint

#11897 Refactor `conda init SHELLS` as argparse choices
  conda/cli/conda_argparse.py
  conda/cli/main_init.py
Labels: cla-signed, sprint

#11591 Fail with a readable error message if PackageCacheRecords are missing
  conda/misc.py
  news/11591-readable-error-message-if-packagecacherecords-missing
  tests/test_misc.py
Labels: source::community, cla-signed

#11818 Avoid a specific case where `conda env update` hangs.
  conda_env/installers/pip.py
  news/11818-conda-hang
Labels: cla-signed

#11841 Download packages in parallel
  conda/base/context.py
  conda/common/io.py
  conda/core/package_cache_data.py
  docs/source/dev-guide/deep-dive-install.md
  tests/core/test_package_cache_data.py
Labels: tag::performance, cla-signed, sprint
