Repository conda/conda, pull requests merged in 2022-12, with the labels that each got.

#12135 Added conda Discourse link
  README.md
Labels: cla-signed, sprint

#12142 Fixes slow running test in the `tests/cli/test_main_notices.py` file
  tests/cli/test_main_notices.py
Labels: cla-signed

#12141 Skip tests when non-code is modified
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  news/12141-skip-testing-non-code
Labels: cla-signed, sprint

#12147 Fix non-code workflow error detected during testing #12144
  .github/workflows/tests-skip.yml
Labels: cla-signed, sprint

#12148 Fix missing __unix virtual package in 22.11
  conda/core/index.py
  conda/plugins/hookspec.py
  conda/plugins/types.py
  conda/plugins/virtual_packages/archspec.py
  conda/plugins/virtual_packages/cuda.py
  conda/plugins/virtual_packages/linux.py
  conda/plugins/virtual_packages/osx.py
  conda/plugins/virtual_packages/windows.py
  news/12148-restore-default-virtual-packages
  tests/core/test_index.py
  tests/plugins/test_manager.py
  tests/plugins/test_virtual_packages.py
Labels: cla-signed

#12152 Release 22.11.1
  .authors.yml
  CHANGELOG.md
  news/12141-skip-testing-non-code
  news/12148-restore-default-virtual-packages
Labels: source::anaconda, cla-signed

#12128 Avoid warning when environment variables have the same value of OS ones
  conda/activate.py
  tests/test_activate.py
Labels: source::community, cla-signed

#12157 Add news file for PR 12128
  news/12128-avoid-warning-when-env-vars-same-value-as-os-values
Labels: cla-signed

#12158 Fix typo in Virtual Packages plugin documentation page
  docs/source/dev-guide/plugins/virtual_packages.rst
Labels: source::anaconda, cla-signed, type::documentation, plugins

#12156 add run_constrained
  recipe/meta.yaml
Labels: source::anaconda, cla-signed, sprint

#12170 Fixes a compatibility bug with darker and black
  .pre-commit-config.yaml
Labels: cla-signed

#12162 Changing English on Skip Testing...
  .github/workflows/tests-skip.yml
Labels: cla-signed

#12180 Use GH Action instead of `on` path filtering
  .github/workflows/tests-skip.yml
  .github/workflows/tests.yml
Labels: cla-signed, sprint

#11949 Fix behavior of `--no-user` flag in `conda init`
  conda/cli/conda_argparse.py
  conda/cli/main_init.py
  news/11949-fix-behavior-of-no-user-flag-in-conda-init
Labels: source::community, cla-signed, duplicate::primary, sprint

#12184 Add Python 3.10 canary build
  recipe/conda_build_config.yaml
Labels: source::anaconda, cla-signed, sprint

#12191 Add missing tqdm dependency to host
  recipe/meta.yaml
Labels: source::anaconda, cla-signed, sprint

#11738 Update enable-tab-completion.rst
  docs/source/user-guide/configuration/enable-tab-completion.rst
  news/11738-update-tab-completion-docs
Labels: cla-signed

#12192 Update solver plugin docstring/example
  conda/plugins/hookspec.py
Labels: cla-signed, plugins, sprint, documentation::reference
