Repository conda/conda, pull requests merged in 2022-06, with the labels that each got.

#11528 Add note about disabling adding to PATH during AllUsers installation (on Windows)
  docs/source/user-guide/install/windows.rst
Labels: cla-signed

#11541 completions have moved to conda-incubator
  docs/source/user-guide/configuration/enable-tab-completion.rst
Labels: cla-signed

#11547 Add missing period to `conda clean`
  conda/cli/main_clean.py
Labels: cla-signed, sprint

#11560 Update Dockerfile + ci-images flow to build multi arch images
  .github/workflows/ci-images.yml
  Dockerfile
Labels: cla-signed

#11568 Rename issue templates
  .github/ISSUE_TEMPLATE/0_bug.yml
  .github/ISSUE_TEMPLATE/1_feature.yml
  .github/ISSUE_TEMPLATE/2_speed_improvement.yml
  .github/ISSUE_TEMPLATE/3_libmamba-solver-feedback.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed, sprint

#11573 Remove `conda.common.url.is_ipv6_address_win_py27`
  conda/common/url.py
  news/11573-remove-is_ipv6_address_win_py27
Labels: cla-signed, sprint

#11578 Remove Repeated `dashlist` Function from `resolve.py`
  conda/plan.py
  conda/resolve.py
  conda/testing/integration.py
Labels: type::tech-debt, cla-signed, sprint

#11462 CEP-6 Channel Notices
  conda/base/constants.py
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/main_create.py
  conda/cli/main_install.py
  conda/cli/main_notices.py
  conda/cli/main_update.py
  conda/cli/python_api.py
  conda/models/channel.py
  conda/notices/__init__.py
  conda/notices/cache.py
  conda/notices/core.py
  conda/notices/http.py
  conda/notices/types.py
  conda/notices/views.py
  conda/testing/fixtures.py
  conda/testing/notices/__init__.py
  conda/testing/notices/fixtures.py
  conda/testing/notices/helpers.py
  conda/utils.py
  conda_env/cli/main_create.py
  conda_env/cli/main_update.py
  docs/source/commands/notices.rst
  news/11462-cep-6-channel-notices
  tests/cli/test_main_info.py
  tests/cli/test_main_notices.py
  tests/conftest.py
  tests/notices/__init__.py
  tests/notices/test_core.py
  tests/notices/test_http.py
  tests/notices/test_types.py
  tests/test_utils.py
Labels: source::anaconda, cla-signed, type::poc

#11584 Update CONTRIBUTING.md: fixing broken link for CLA license contributors
  CONTRIBUTING.md
Labels: source::anaconda, type::documentation

#11571 Mark `conda.lock` as pending deprecation
  conda/lock.py
  news/11571-pendingdeprecation-conda.lock
Labels: source::anaconda, cla-signed, sprint

#11533 refactor SubdirData._process_raw_repodata_str
  conda/core/subdir_data.py
Labels: source::anaconda, cla-signed

#11588 Fix for broken Windows test runners on CI
  conda/testing/notices/helpers.py
  tests/cli/test_main_notices.py
Labels: cla-signed, sprint

#11592 Fixed outstanding spacing issue in conda init help text.
  conda/cli/conda_argparse.py
Labels: cla-signed, sprint
