Repository conda/conda, pull requests merged in 2022-02, with the labels that each got.

#11182 Introduce `CONDA_SITE_PACKAGES`
  conda/__init__.py
  conda/activate.py
  conda/base/context.py
  conda/utils.py
  tests/core/test_initialize.py
  tests/test_activate.py
  tests/test_create.py
Labels: cla-signed

#11181 [libmamba] Refactor integration test helpers
  conda/gateways/logging.py
  conda/testing/helpers.py
  conda/testing/integration.py
  conda/testing/solver_helpers.py
  tests/cli/test_cli_install.py
  tests/conda_env/test_create.py
  tests/core/test_package_cache_data.py
  tests/test_activate.py
  tests/test_cli.py
  tests/test_create.py
  tests/test_export.py
  tests/test_history.py
  tests/test_link_order.py
  tests/test_priority.py
  tests/test_utils.py
Labels: cla-signed, solver::libmamba

#11038 Instantiate separate S3 session for thread-safety.
  conda/gateways/connection/adapters/s3.py
Labels: type::bug, cla-signed, severity::4, backlog

#11187 [libmamba] Error out if libmamba is chosen but unavailable
  conda/core/solve.py
Labels: cla-signed, solver::libmamba

#11188 Disable autofix for pre-commit.ci.
  .pre-commit-config.yaml
Labels: cla-signed

#11195 Fix the canary release action to not check for team membership.
  .github/workflows/builds-review.yaml
Labels: cla-signed

#11215 Allow `conda run` to work in read-only environments.
  conda/cli/main_run.py
  conda/utils.py
  tests/test_cli.py
Labels: cla-signed

#11221 Clarify on AIE messaging in download.rst
  docs/source/user-guide/install/download.rst
Labels: cla-signed

#11236 Bump up versions in deps-only tests.
  tests/test_create.py
Labels: type::bug, os::windows, cla-signed

#11233 `devenv`: env per Python version and side by side OS installs
  .gitattributes
  conda.recipe/bld.bat
  dev/start
  dev/start.bat
Labels: cla-signed

#11189 Improve command line argument quoting
  conda/utils.py
  tests/test_utils.py
Labels: cla-signed

#11237 Fix conda environment variable echo, update example versions
  docs/source/user-guide/tasks/manage-environments.rst
Labels: cla-signed

#11243 Don't make devenv dir when running `dev/start --dry-run`
  dev/start
  dev/start.bat
Labels: cla-signed

#11248 Rename lock workflow
  .github/workflows/lock.yml
Labels: cla-signed

#11251 Flatten `dev\start.bat`
  dev/start.bat
Labels: cla-signed

#11255 Do not auto activate base before activating devenv
  conda/core/initialize.py
  dev/start
  dev/start.bat
Labels: cla-signed

#11258 Add concurrency group to cancel GHA runs on repeated pushes to branch/PR.
  .github/workflows/ci.yml
Labels: cla-signed

#11260 Change overly verbose info log to debug.
  conda/common/io.py
Labels: cla-signed

#11265 Only run GHAs on non-forks
  .github/workflows/builds-canary.yaml
  .github/workflows/builds-review.yaml
  .github/workflows/ci-images.yml
  .github/workflows/ci.yml
Labels: cla-signed

#11268 Fixed : Broken link while referring to YAML syntax #11261
  docs/source/user-guide/configuration/use-condarc.rst
Labels: cla-signed
