Repository conda/conda, pull requests merged in 2022-03, with the labels that each got.

#11273 Relax python constrain in --only-deps test.
  tests/test_create.py
Labels: cla-signed

#11282 Experimental solver confirmation
  conda/base/context.py
  conda/cli/common.py
Labels: cla-signed, solver::libmamba

#11286 ci-skip.yml to circumvent skipped required checks
  .github/workflows/ci-skip.yml
  .github/workflows/ci.yml
Labels: cla-signed

#11287 Including strategy matrix in skipped checks
  .github/workflows/ci-skip.yml
Labels: cla-signed

#11278 docs: update profile examples
  docs/source/user-guide/configuration/non-standard-certs.rst
Labels: cla-signed

#11289 Report update status in `source ./dev/start --dry-run`
  dev/start
Labels: cla-signed

#11267 Remove five.py and update metaclass definitions
  conda/auxlib/_vendor/five.py
  conda/auxlib/compat.py
  conda/auxlib/entity.py
  conda/auxlib/factory.py
  conda/common/compat.py
  conda/common/configuration.py
  conda/core/package_cache_data.py
  conda/core/path_actions.py
  conda/core/prefix_data.py
  conda/core/subdir_data.py
  conda/gateways/connection/session.py
  conda/models/channel.py
  conda/models/dist.py
  conda/models/match_spec.py
  conda/models/version.py
Labels: cla-signed

#11295 Authors update
  .authors.yml
  rever.xsh
Labels: cla-signed

#11276 Libmamba issue form
  .github/ISSUE_TEMPLATE/libmamba-solver-feedback.yml
  .github/labels.yml
Labels: cla-signed, solver::libmamba

#11288 Remove old CLA code
  .cla-signers
  .exempt-commits
  .github-map
  utils/cla.py
Labels: cla-signed

#11299 Document `conda run`
  docs/source/commands/run.rst
Labels: cla-signed

#11302 Update conda run docs to not mention double dash.
  conda/cli/conda_argparse.py
  docs/source/user-guide/tasks/manage-python.rst
Labels: cla-signed

#11123 Add support for prelink_message which is already available in conda-build
  .gitpod.yml
  CONTRIBUTING.md
  conda/core/link.py
  conda/testing/fixtures.py
  dev/linux/integration.sh
  dev/windows/integration.bat
  tests/cli/test_cli_install.py
  tests/conftest.py
  tests/test-recipes/pre_link_messages_package/message-from-pkg.txt
  tests/test-recipes/pre_link_messages_package/message-from-pkg2.txt
  tests/test-recipes/pre_link_messages_package/meta.yaml
Labels: type::feature, source::community, pending::feedback, cli, cla-signed, tag::compatibility, severity::4, backlog

#11296 Release 4.12.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/gh-11168-get-comspec
  news/gh-11172-validate-prefix
  news/gh-11182-CONDA_SOURCE_ROOT
Labels: cla-signed

#11304 Partially revert ce5a8a703c9ac1d2f159f6cbf3a67564236fb261.
  conda/base/context.py
Labels: cla-signed

#11313 Revive epic label
  .github/labels.yml
Labels: cla-signed

#11314 Add `[plugins::activate]` & `[plugins::init]` labels
  .github/labels.yml
Labels: cla-signed

#11336 Include docs for `conda compare`
  docs/source/commands/compare.rst
Labels: cla-signed

#11290 Replace custom `conda._vendor` with vendoring
  .pre-commit-config.yaml
  conda/_vendor/README.rst
  conda/_vendor/appdirs.LICENSE.txt
  conda/_vendor/appdirs.py
  conda/_vendor/boltons/LICENSE
  conda/_vendor/boltons/setutils.py
  conda/_vendor/boltons/timeutils.py
  conda/_vendor/cpuinfo.py
  conda/_vendor/cpuinfo/__init__.py
  conda/_vendor/cpuinfo/cpuinfo.py
  conda/_vendor/distro.LICENSE.txt
  conda/_vendor/distro.py
  conda/_vendor/frozendict/LICENSE.txt
  conda/_vendor/frozendict/__init__.py
  conda/_vendor/py-cpuinfo.LICENSE
  conda/_vendor/six.LICENSE
  conda/_vendor/six.py
  conda/_vendor/toolz/__init__.py
  conda/_vendor/toolz/dicttoolz.py
  conda/_vendor/toolz/itertoolz.py
  conda/_vendor/toolz/recipes.py
  conda/_vendor/tqdm/LICENCE
  conda/_vendor/tqdm/__init__.py
  conda/_vendor/tqdm/auto.py
  conda/_vendor/tqdm/contrib/__init__.py
  conda/_vendor/tqdm/contrib/concurrent.py
  conda/_vendor/tqdm/contrib/itertools.py
  conda/_vendor/tqdm/utils.py
  conda/_vendor/tqdm/version.py
  conda/_vendor/urllib3/LICENSE.txt
  conda/_vendor/urllib3/__init__.py
  conda/_vendor/urllib3/exceptions.py
  conda/_vendor/urllib3/util/__init__.py
  conda/_vendor/urllib3/util/url.py
  conda/_vendor/vendor.txt
  conda/auxlib/_vendor/__init__.py
  conda/auxlib/_vendor/boltons/__init__.py
  conda/auxlib/_vendor/boltons/timeutils.py
  conda/auxlib/compat.py
  conda/auxlib/decorators.py
  conda/auxlib/entity.py
  conda/gateways/anaconda_client.py
  pyproject.toml
  tools/vendoring/patches/cpuinfo.patch
  tools/vendoring/patches/distro.patch
  tools/vendoring/patches/frozendict.patch
  tools/vendoring/patches/toolz.patch
  tools/vendoring/patches/tqdm.patch
  tools/vendoring/patches/urllib3.exceptions.patch
  tools/vendoring/patches/urllib3.patch
  tools/vendoring/patches/urllib3.util.patch
Labels: cla-signed

#10992 Add Python 3.10 as a test target.
  .github/workflows/ci.yml
  conda/_vendor/boltons/setutils.py
  conda/_vendor/boltons/timeutils.py
  conda/_vendor/vendor.txt
  tests/test_activate.py
  tests/test_create.py
Labels: cla-signed

#11309 Remove deprecated `conda.cli.activate`
  conda/activate.py
  conda/cli/activate.py
  conda/cli/main.py
  conda/common/compat.py
  conda/testing/helpers.py
  news/11309-remove-conda.cli.activate
  tests/test_activate.py
Labels: cla-signed

#11322 Remove deprecated `conda.compat`
  conda/compat.py
  news/11322-remove-conda.compat
Labels: cla-signed

#11325 Remove deprecated `conda.cli.main_help`
  conda/cli/conda_argparse.py
  conda/cli/main_help.py
  conda/cli/python_api.py
  news/11325-remove-conda.cli.main_help
  tests/cli/test_conda_argparse.py
Labels: cla-signed

#11356 Remove expensive conda-build autouse fixture
  tests/cli/test_cli_install.py
  tests/conftest.py
  tests/test_activate.py
Labels: cla-signed

#11312 Correction of RegisterPython description in Windows Installer arguements
  docs/source/user-guide/install/windows.rst
Labels: cla-signed

#11378 Add python constraint back for `--update-deps --only-deps`
  tests/test_create.py
Labels: cla-signed

#11349 Remove unused `auxlib` parts
  conda/auxlib/configuration.py
  conda/auxlib/crypt.py
  conda/auxlib/deprecation.py
  conda/auxlib/factory.py
  conda/auxlib/path.py
  conda/cli/main_compare.py
  conda_env/cli/common.py
Labels: cla-signed

#11351 Reorg main_clean
  conda/cli/main_clean.py
  conda/exports.py
  conda/gateways/disk/link.py
  news/11351-reorg-conda.cli.main_clean
  tests/core/test_path_actions.py
  tests/gateways/disk/test_link.py
Labels: cla-signed

#11384 Add news for `auxlib` removals
  news/11349-remove-unused-conda.auxlib
Labels: cla-signed

#11381 Remove duplicated instruction in manage-python.rst
  docs/source/user-guide/tasks/manage-python.rst
Labels: cla-signed

#11360 Reorg + new tests for main_clean
  conda/base/constants.py
  tests/cli/test_main_clean.py
  tests/conftest.py
  tests/test_create.py
Labels: cla-signed

#11373 Issue 11334 replace vendored urllib3
  conda/_vendor/urllib3/LICENSE.txt
  conda/_vendor/urllib3/__init__.py
  conda/_vendor/urllib3/exceptions.py
  conda/_vendor/urllib3/util/__init__.py
  conda/_vendor/urllib3/util/url.py
  conda/common/url.py
  conda/models/channel.py
  news/11334-replace-urllib3-with-urllib
  tests/common/test_url.py
Labels: cla-signed
