Repository conda/conda, pull requests merged in 2022-10, with the labels that each got.

#11911 Enable one single test for linux-{aarch64, ppc64le}
  .github/workflows/ci.yml
Labels: cla-signed

#11924 Update xprocess minio pattern.
  conda/testing/gateways/fixtures.py
Labels: cla-signed, sprint

#11768 Updated conda cheatsheet for 4.14.0 release.
  docs/source/user-guide/cheatsheet.rst
  docs/source/user-guide/cheatsheets/conda-4.14.pdf
  docs/source/user-guide/conda-cheatsheet.pdf
  news/11757-conda-cheatsheet-needs-updated-for-v4140
Labels: cla-signed

#11852 Fix for conda update and install issue related to notices
  conda/base/constants.py
  conda/cli/main_notices.py
  conda/notices/core.py
  conda/notices/fetch.py
  conda/notices/types.py
  conda/testing/notices/helpers.py
  tests/cli/test_main_notices.py
  tests/notices/test_core.py
  tests/notices/test_fetch.py
Labels: cla-signed

#11928 Minor auto fixes from pre-commit.com hooks
  conda/notices/core.py
Labels: cla-signed, sprint

#11929 Introduce git-blame-ignore-revs file, add pyupgrade commit to it
  .git-blame-ignore-revs
Labels: cla-signed

#11374 Check for conda before calling shell hook
  conda/core/initialize.py
  news/11374-check-conda-exe-before-use
  tests/core/test_initialize.py
Labels: cla-signed

#11943 Removing an outdated piece of documentation (Windows XP)
  docs/source/redirects.rst
  docs/source/user-guide/configuration/index.rst
  docs/source/user-guide/configuration/use-winxp-with-proxy.rst
  docs/source/winxp-proxy.rst
Labels: cla-signed, type::documentation

#11945 Fix Some Documentation Formatting
  docs/source/user-guide/install/index.rst
Labels: source::anaconda, cla-signed, type::documentation

#11959 restore CondaMultiError from package downloads
  conda/core/package_cache_data.py
  tests/core/test_package_cache_data.py
Labels: cla-signed

#11913 substitute for toolz.groupby
  conda/cli/main_config.py
  conda/common/iterators.py
  conda/common/pkg_formats/python.py
  conda/core/package_cache_data.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/exceptions.py
  conda/history.py
  conda/models/match_spec.py
  conda/plan.py
  conda/resolve.py
  conda_env/env.py
  tests/core/test_path_actions.py
  tests/test_create.py
Labels: cla-signed, sprint

#9946 UTF 16 and UTF 32 fixes
  conda/core/portability.py
  tests/test_install.py
Labels: cla-signed

#11889 Replace "experimental solver" with just "solver"
  .github/ISSUE_TEMPLATE/3_libmamba-solver-feedback.yml
  conda/base/constants.py
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/main.py
  conda/cli/main_config.py
  conda/common/configuration.py
  conda/core/solve.py
  conda_env/cli/main_create.py
  conda_env/cli/main_remove.py
  conda_env/cli/main_update.py
  news/11889-remove-experimental-label
Labels: cla-signed

#11979 Remove vendored six.py and dependencies on it.
  conda/_vendor/six.LICENSE
  conda/_vendor/six.py
  conda/_vendor/vendor.txt
  conda/auxlib/compat.py
  conda/auxlib/decorators.py
  conda/auxlib/entity.py
  conda/auxlib/type_coercion.py
  conda/exports.py
  news/11979-remove-vendored-six
Labels: cla-signed

#11796 Improve CLI warning about updating conda
  conda/core/solve.py
  news/11300-improve-cli-warning-conda-update
Labels: cla-signed

#11996 Fix error output bug in rename tests
  tests/cli/test_main_rename.py
Labels: type::bug, cla-signed, type::testing

#12002 Repodata gateway merged
  conda/core/package_cache_data.py
  conda/core/repo.py
  conda/core/subdir_data.py
  conda/testing/integration.py
  dev/linux/integration.sh
  dev/linux/unit.sh
  tests/core/test_solve.py
  tests/core/test_subdir_data.py
  tests/requirements.txt
  tests/test_create.py
  tests/test_fetch.py
Labels: cla-signed

#11849 Add comment to explain .bashrc vs .bash_profile
  conda/core/initialize.py
  news/11839-document-bashrc-bashprofile
Labels: cla-signed

#12019 tests: use readline instead of regex capture to avoid deadlock
  .github/workflows/ci.yml
  dev/macos/setup.sh
  tests/test_activate.py
Labels: cla-signed

#12021 simplify minio cache key
  .github/workflows/ci.yml
Labels: cla-signed

#12022 remove python 3 try/except import
  conda/common/url.py
Labels: cla-signed

#11960 Merge plugins feature branch into main.
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/main.py
  conda/exceptions.py
  conda/plugins/__init__.py
  docs/requirements.txt
  docs/source/conf.py
  docs/source/dev-guide/index.rst
  docs/source/dev-guide/plugin-api/index.rst
  docs/source/dev-guide/plugin-api/subcommands.rst
  news/11435-plugins-mechanism
  recipe/meta.yaml
  setup.py
  tests/cli/test_conda_argparse.py
  tests/cli/test_main_rename.py
  tests/conda_env/test_cli.py
  tests/plugins/conftest.py
  tests/plugins/test_subcommands.py
  tests/requirements.txt
Labels: cla-signed, plugins, sprint

#12031 typing changes for activate
  conda/activate.py
  tests/test_create.py
Labels: cla-signed

#12020 Remove `toolz.itertoolz.concatv`
  LICENSE.txt
  Makefile
  conda/base/context.py
  conda/common/configuration.py
  conda/common/pkg_formats/python.py
  conda/core/index.py
  conda/core/link.py
  conda/core/package_cache_data.py
  conda/core/solve.py
  conda/models/channel.py
  conda/models/match_spec.py
  conda/plan.py
  conda_env/env.py
  news/12020-stop-using-toolz.itertoolz.concatv
  setup.cfg
  tests/test_activate.py
Labels: cla-signed, sprint

#12023 Convert `conda.core.initialize` unittest to pytest
  tests/core/test_initialize.py
Labels: cla-signed, sprint
