Repository conda/conda, pull requests merged in 2022-05, with the labels that each got.

#11443 Updated conda cheatsheet.
  docs/source/user-guide/cheatsheet.rst
  docs/source/user-guide/cheatsheets/conda-4.12.pdf
  docs/source/user-guide/cheatsheets/conda-4.6.pdf
  docs/source/user-guide/conda-cheatsheet.pdf
Labels: cla-signed

#11448 Fix typos
  CHANGELOG.md
  conda/activate.py
  conda/auxlib/entity.py
  conda/base/context.py
  conda/cli/python_api.py
  conda/common/_logic.py
  conda/common/pkg_formats/python.py
  conda/core/portability.py
  conda/core/prefix_data.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/gateways/connection/adapters/ftp.py
  conda/models/version.py
  conda/resolve.py
  conda/shell/conda.xsh
  conda_env/cli/main_export.py
  conda_env/specs/requirements.py
  docs/source/_static/js/panzoom.js
  docs/source/user-guide/configuration/use-condarc.rst
  tests/core/test_subdir_data.py
  tests/test_logic.py
Labels: cla-signed

#11415 extend user-agent if solver != default
  conda/base/context.py
  news/11413-add-user-agent-solver
Labels: cla-signed

#11433 Define optional exception attribute to bypass the retry logic
  conda/cli/install.py
Labels: cla-signed

#11453 Drop Python 3.6 support
  docs/source/user-guide/tasks/manage-environments.rst
  docs/source/user-guide/tasks/manage-pkgs.rst
  docs/source/user-guide/tasks/manage-python.rst
  docs/source/user-guide/tasks/use-conda-with-travis-ci.rst
  news/11453-drop-python-3.6
  setup.py
Labels: cla-signed

#11455 Catch all exceptions in context.user_agent
  conda/base/context.py
  news/11455-user-agent-ignore-importerror
Labels: cla-signed

#11461 Use `_ENVEXE` to init/activate devenv
  dev/start
  dev/start.bat
Labels: cla-signed

#11469 Remove `test_init_dev_and_NoBaseEnvironmentError`
  tests/test_create.py
Labels: cla-signed, type::testing

#11446 'Accept', not 'Content-Type' in GET header
  conda/core/subdir_data.py
Labels: cla-signed

#11400 Add informational Codecov status checks
  .codecov.yml
Labels: cla-signed

#11059 Start deep dive docs
  docs/source/dev-guide/deep-dive-activation.md
  docs/source/dev-guide/deep-dive-context.md
  docs/source/dev-guide/deep-dive-install.md
  docs/source/dev-guide/deep-dive-solvers.md
  docs/source/dev-guide/index.rst
  docs/source/dev-guide/techspec-solver-state.md
  docs/source/img/conda-install-deep-dive.png
  docs/source/img/solver-deep-dive-1.png
  docs/source/img/solver-deep-dive-2.png
  docs/source/img/solver-deep-dive-3.png
  docs/source/user-guide/concepts/conda-performance.rst
  docs/source/user-guide/concepts/environments.rst
  docs/source/user-guide/configuration/use-condarc.rst
Labels: cla-signed, type::documentation, sprint, sync::anaconda

#11478 Release 4.13.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/11309-remove-conda.cli.activate
  news/11322-remove-conda.compat
  news/11323-remove-conda.install
  news/11325-remove-conda.cli.main_help
  news/11334-replace-urllib3-with-urllib
  news/11349-remove-unused-conda.auxlib
  news/11351-reorg-conda.cli.main_clean
  news/11387-conda-clean-logfiles
  news/11393-bump-cpuinfo-version
  news/11398-replace-conda.auxlib.collection.frozendict
  news/11413-add-user-agent-solver
  news/11422-conda-run-live-stream-alias
  news/11424-remove-unused-exceptions
  news/11425-combine-exceptions
  news/11440-improve-http-error-message
  news/11453-drop-python-3.6
  news/11455-user-agent-ignore-importerror
  rever.xsh
Labels: cla-signed, sprint

#11508 Update documentation from bare conda.io domain to docs.conda.io
  README.rst
Labels: cla-signed

#11490 Remove `conda.cli.common.ensure_name_or_prefix`
  conda/cli/common.py
  conda/cli/conda_argparse.py
  conda/cli/install.py
  news/11490-deprecate-conda.cli.common.ensure_name_or_prefix
Labels: cla-signed, sprint
