Repository conda/conda, pull requests merged in 2022-07, with the labels that each got.

#11595 Replace `conda_env.cli.common.stdout_json` with `conda.cli.common.stdout_json`
  conda_env/cli/common.py
  conda_env/cli/main_export.py
  news/11595-pendingdeprecation-conda_env.cli.common.stdout_json
Labels: cla-signed, sprint

#11594 Replace `conda_env.cli.common.get_prefix` with `conda.base.context.determine_target_prefix`
  conda/base/context.py
  conda_env/cli/common.py
  conda_env/cli/main_create.py
  conda_env/cli/main_export.py
  conda_env/cli/main_update.py
  conda_env/cli/main_vars.py
  news/11594-pendingdeprecation-get_prefix
Labels: cla-signed, sprint

#11601 Mention invalid package name in error message
  conda_env/specs/binstar.py
  news/11601-mention-invalid-name-in-error-message
  tests/conda_env/specs/test_binstar.py
Labels: cla-signed

#11496 Add new `rename` command
  conda/base/constants.py
  conda/base/context.py
  conda/cli/common.py
  conda/cli/conda_argparse.py
  conda/cli/install.py
  conda/cli/main_rename.py
  conda/gateways/disk/update.py
  conda/notices/types.py
  conda/testing/helpers.py
  docs/source/commands/rename.rst
  docs/source/dev-guide/deep-dive-solvers.md
  news/11496-new-rename-command
  tests/base/test_context.py
  tests/cli/test_main_rename.py
  tests/conda_env/test_cli.py
Labels: source::anaconda, cla-signed

#11631 Remove unused test clauses
  tests/conda_env/test_cli.py
Labels: cla-signed, sprint

#11598 Fix repeated `conda config` in documented commands
  docs/source/user-guide/tasks/manage-python.rst
Labels: cla-signed

#11629 docs: fix simple typo, enventually -> eventually
  conda/misc.py
Labels: cla-signed

#11611 Updated conda env create CLI help text.
  conda_env/cli/main_create.py
  news/9396-outdated-examples-section-in-help-for-conda-env-create
Labels: cla-signed

#11625 Suggest conda --help instead of non-existing 'conda help'
  conda/exceptions.py
  news/11625-correct-conda-help-err-msg
Labels: cla-signed

#11630 Fix empty environment.yml
  conda/exceptions.py
  conda_env/env.py
  conda_env/specs/yaml_file.py
  news/11542-conda-crashes-on-empty-environment
  tests/conda_env/test_cli.py
Labels: cla-signed

#11570 Modify code to refer to `main` branch instead of `master`
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/builds-canary.yaml
  .github/workflows/ci-images.yml
  .github/workflows/ci.yml
  README.md
  conda_env/cli/main_create.py
  docs/source/release-notes.md
  news/11570-rename-master-to-main
  tests/conda_env/__init__.py
  tests/conda_env/test_cli.py
  tests/conda_env/test_env.py
Labels: source::anaconda, cla-signed, sprint

#11645 Update gitpod/images to use main branch
  .devcontainer.json
  .github/workflows/ci.yml
  .gitpod.yml
Labels: cla-signed, sprint

#11604 Adding new documentation article on writing tests
  docs/source/dev-guide/index.rst
  docs/source/dev-guide/writing-tests/index.rst
  docs/source/dev-guide/writing-tests/integration-tests.md
Labels: cla-signed

#11564 Separate `SSLError` from `HTTPError`
  conda/core/subdir_data.py
  conda/exceptions.py
  conda/gateways/connection/download.py
  news/11564-ssl-errors
  tests/core/test_subdir_data.py
Labels: source::anaconda, cla-signed, sprint

#11597 Deprecate `conda.auxlib.decorators.memoize` in favor of `functools.lru_cache`
  conda/auxlib/decorators.py
  conda/base/context.py
  conda/cli/find_commands.py
  conda/common/_os/linux.py
  conda/common/path.py
  conda/common/serialize.py
  conda/common/url.py
  conda/exports.py
  conda/gateways/disk/test.py
  conda/gateways/logging.py
  conda/resolve.py
  conda/testing/helpers.py
  conda/testing/integration.py
  conda/utils.py
  news/11597-pendingdeprecation-conda.auxlib.decorators.memoize
  tests/models/test_prefix_graph.py
  tests/test_activate.py
Labels: cla-signed, sprint

#11655 Add missing `CondaError` import
  conda/cli/main.py
Labels: cla-signed, sprint

#11643 require requests >=2.20.1, drop monkeypatch
  conda/gateways/connection/__init__.py
  recipe/meta.yaml
  setup.py
Labels: cla-signed, sprint

#11626 Support CUDA detection on WSL
  conda/common/cuda.py
  news/11626-cuda-wsl2
Labels: cla-signed

#11647 Rename `whitelist_channels` to `allowlist_channels`
  conda/auxlib/entity.py
  conda/base/context.py
  conda/core/index.py
  conda/core/subdir_data.py
  conda/exceptions.py
  docs/source/user-guide/configuration/use-condarc.rst
  news/11647-allowlist_channels
  tests/base/test_context.py
  tests/core/test_index.py
  tests/data/build-index2-json.py
  tests/data/build-index4-json.py
  tests/data/build-index5-json.py
  tests/integration/proxy/squid.conf
  tests/models/test_channel.py
Labels: cla-signed, sprint

#11660 Bump black's python versions
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
Labels: cla-signed, sprint

#11636 Fix typo in `conda create` help
  conda/cli/conda_argparse.py
Labels: source::community, cla-signed, type::documentation

#11670 Fix recursion in error in `check_allowlist` alias
  conda/core/index.py
Labels: cla-signed

#11659 Forward slashes in channel names breaks channel notice cache
  conda/notices/cache.py
  conda/notices/types.py
  conda/testing/notices/helpers.py
  tests/cli/test_main_notices.py
Labels: source::anaconda, cla-signed

#11658 add usedforsecurity=False for hashlib.md5 for FIPS compliance
  conda/core/subdir_data.py
  news/11658-add-fips-md5-support
Labels: source::community, cla-signed
