Repository conda/conda, pull requests merged in 2022-01, with the labels that each got.

#11084 Prefix state renovations
  .github/workflows/ci.yml
  conda/auxlib/__init__.py
  conda/base/constants.py
  conda/base/context.py
  conda/core/solve/README.md
  conda/core/solve/__init__.py
  conda/core/solve/classic.py
  conda/core/solve/libmamba.py
  conda/core/solve/libmamba2.py
  conda/core/solve/libmamba_utils.py
  conda/core/solve/state.py
  dev/linux/experimental-resolver.sh
  dev/windows/experimental-resolver.bat
  tests/cli/test_cli_install.py
  tests/core/test_solve.py
  tests/core/test_state.py
  tests/requirements.txt
  tests/test_create.py
  tests/test_solvers.py
Labels: cla-signed, solver::behavior, solver::libmamba

#10875 Add macOS to CI
  .github/workflows/ci.yml
  dev/macos/integration.sh
  dev/macos/unit.sh
  dev/windows/setup.bat
  tests/test_create.py
Labels: type::bug, source::anaconda, severity::3, cla-signed, os::macos

#11130 Update git:// to git+https:// in tests (GitHub policy changed)
  tests/test_create.py
Labels: cla-signed

#11129 [libmamba] Fix macOS failures
  dev/macos/experimental-resolver.sh
  tests/requirements.txt
Labels: cla-signed, solver::libmamba

#11148 Remove hash from colors
  .github/labels.yml
Labels: cla-signed

#11149 Colors need to be in quotes since some are numbers
  .github/labels.yml
Labels: cla-signed

#11157 Fix `labels.yml` syntax error
  .github/labels.yml
Labels: cla-signed

#11158 More local labels
  .github/labels.yml
Labels: cla-signed

#11132 [Libmamba] Write debug logs to disk
  conda/base/context.py
  conda/cli/main.py
  conda/common/io.py
  conda/core/solve/libmamba2.py
  conda/core/solve/libmamba_utils.py
  conda/core/solve/state.py
  conda/gateways/logging.py
  conda/resolve.py
  tests/common/test_io.py
Labels: cla-signed, solver::libmamba

#11164 Add type::installer & type::packaging, revert build::review
  .github/labels.yml
Labels: cla-signed

#11165 Modify `quote_for_shell` signature
  conda/gateways/disk/delete.py
  conda/utils.py
  tests/test_activate.py
Labels: cla-signed

#11013 Remove unnecessary conditional
  setup.py
Labels: cla-signed

#11168 Rework `ensure_comspec_set` into `get_comspec`
  conda/core/link.py
  conda/utils.py
  news/gh-11168-get-comspec
Labels: cla-signed

#11135 Review builds on PR labelling
  .github/workflows/build-upload-pkgs.yaml
  .github/workflows/builds-canary.yaml
  .github/workflows/builds-review.yaml
Labels: cla-signed

#11172 Refactor `is_valid_prefix` into `validate_prefix`
  conda/cli/common.py
  conda/cli/main_run.py
  news/gh-11172-validate-prefix
Labels: cla-signed

#10993 Build Docker image for Linux with Python 3.10.
  .github/workflows/ci-images.yml
Labels: type::feature, cla-signed, severity::4, backlog, sync::anaconda

#11173 Cleanup `conda.cli.main_run.execute`
  conda/cli/main_run.py
Labels: cla-signed

#11163 [Libmamba] Remove code that now belongs to `conda-incubator/conda-libmamba-solver`
  .github/workflows/ci.yml
  conda/base/constants.py
  conda/core/solve.py
  conda/core/solve/README.md
  conda/core/solve/__init__.py
  conda/core/solve/libmamba.py
  conda/core/solve/libmamba2.py
  conda/core/solve/libmamba_utils.py
  conda/core/solve/state.py
  conda/exports.py
  conda/testing/__init__.py
  conda/testing/cases.py
  conda/testing/decorators.py
  conda/testing/helpers.py
  conda/testing/solver_helpers.py
  dev/windows/setup.bat
  tests/base/test_context.py
  tests/cli/test_cli_install.py
  tests/core/test_initialize.py
  tests/core/test_solve.py
  tests/core/test_state.py
  tests/models/test_prefix_graph.py
  tests/test_activate.py
  tests/test_cli.py
  tests/test_create.py
  tests/test_history.py
  tests/test_info.py
  tests/test_install.py
  tests/test_logic.py
  tests/test_plan.py
  tests/test_resolve.py
  tests/test_solvers.py
  tests/test_utils.py
Labels: cla-signed

#11179 Remove unnecessary `on_win` arg for `conda.utils.wrap_subprocess_call`
  conda/cli/main_run.py
  conda/core/link.py
  conda/gateways/subprocess.py
  conda/utils.py
Labels: cla-signed
