Repository conda/conda, pull requests merged in 2023-08, with the labels that each got.

#12946 add note about yaml extension in .condarc docs
  docs/source/user-guide/configuration/use-condarc.rst
Labels: cla-signed

#12951 Bump default devenv Python to 3.10
  dev/start
  dev/start.bat
Labels: cla-signed

#12835 [docs] Update manage-environments.rst
  docs/source/user-guide/tasks/manage-environments.rst
Labels: cla-signed

#12961 Refactor private channel test
  tests/test-recipes/private_package/meta.yaml
  tests/test_create.py
Labels: cla-signed

#12950 Port doctor CLI tests to conda_cli fixture.
  docs/source/dev-guide/writing-tests/integration-tests.md
  tests/plugins/subcommands/doctor/test_cli.py
  tests/plugins/subcommands/doctor/test_health_checks.py
Labels: cla-signed

#12986 Fix `test_s3_server` failure
  conda/testing/gateways/fixtures.py
  news/12986-fix-S3-bucket-name
Labels: cla-signed

#12988 Default `--json` & `--debug` to `NULL`
  conda/cli/conda_argparse.py
  news/12988-CONDA_JSON
Labels: cla-signed

#12992 Remove MinIO pin
  .github/workflows/images.yml
  .github/workflows/tests.yml
  conda/testing/gateways/fixtures.py
  tests/gateways/test_connection.py
Labels: cla-signed

#13006 Find `conda-*` executables on `PATH`
  conda/cli/find_commands.py
  news/13006-non-base-plugins
Labels: cla-signed

#13009 Release 23.7.3
  .authors.yml
  CHANGELOG.md
  news/13006-non-base-plugins
Labels: cla-signed

#13010 Merge `23.7.x` branch back into `main`
  .authors.yml
  CHANGELOG.md
  conda/cli/find_commands.py
Labels: cla-signed

#9614 Make `conda env update --prune` ignore history specs.
  conda/core/solve.py
  news/9614-prune-ignores-history-specs
  tests/core/test_solve.py
Labels: source::community, cla-signed

#12981 gateways/repodata: remove load/save/read_mod_and_etag
  conda/common/toposort.py
  conda/core/subdir_data.py
  conda/gateways/repodata/__init__.py
  tests/core/test_subdir_data.py
  tests/data/build-index2-json.py
  tests/gateways/test_jlap.py
  tests/gateways/test_repodata_gateway.py
  tests/plugins/test_manager.py
  tests/test_fetch.py
Labels: cla-signed

#12994 Handle jlap response without request e.g. for file:///
  conda/gateways/repodata/jlap/fetch.py
  news/12966-jlap-file-uri
  tests/gateways/test_jlap.py
Labels: cla-signed

#12996 Lock repodata cache by default
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/gateways/repodata/lock.py
  news/12920-lock-default
  tests/gateways/test_repodata_lock.py
Labels: cla-signed

#12982 Do not show download bars in non interactive runs
  conda/common/io.py
  conda/core/package_cache_data.py
  news/12982-no-progress-bars-in-logs
Labels: cla-signed

#13028 Add `tag::update` label
  .github/labels.yml
Labels: cla-signed

#12911 Auth handler plugin hook
  conda/gateways/connection/download.py
  conda/gateways/connection/session.py
  conda/gateways/repodata/__init__.py
  conda/gateways/repodata/jlap/interface.py
  conda/notices/fetch.py
  conda/plugins/__init__.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/plugins/types.py
  conda/testing/notices/fixtures.py
  conda/testing/notices/helpers.py
  conda/trust/signature_verification.py
  docs/source/dev-guide/plugins/auth_handlers.rst
  docs/source/dev-guide/plugins/index.rst
  news/12911-auth-handler-plugin-hook
  tests/cli/test_main_notices.py
  tests/gateways/test_connection.py
  tests/gateways/test_jlap.py
  tests/notices/test_core.py
  tests/notices/test_fetch.py
  tests/plugins/test_auth_handlers.py
  tests/plugins/test_post_commands.py
  tests/plugins/test_pre_commands.py
Labels: cla-signed

#12985 Inject new detailed verbosity level
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/main.py
  conda/cli/main_clean.py
  conda/cli/main_info.py
  conda/cli/main_search.py
  conda/core/initialize.py
  conda/core/link.py
  conda/core/package_cache_data.py
  conda/core/solve.py
  conda/exception_handler.py
  conda/exceptions.py
  conda/gateways/logging.py
  conda/gateways/subprocess.py
  conda/plugins/subcommands/doctor/cli.py
  conda/testing/__init__.py
  conda/testing/integration.py
  conda_env/cli/main.py
  conda_env/installers/pip.py
  news/12985-verbosity
  tests/cli/test_main_run.py
Labels: cla-signed

#13025 Ignore setup output for `tests/test_activate.py::test_stacking`
  tests/test_activate.py
Labels: cla-signed

#12889 Directly suppress use of binstar token when fetching trust metadata
  conda/trust/signature_verification.py
  news/12889-trust-metadata-fetch-auth
Labels: cla-signed, tag::artifact-verification

#13039 Fix typo in activation.md
  docs/source/dev-guide/deep-dives/activation.md
Labels: cla-signed

#12924 Add a config option for environment registration
  conda/base/context.py
  conda/core/envs_manager.py
  news/12924-context-register-envs
  tests/cli/test_main_rename.py
  tests/conftest.py
  tests/core/test_envs_manager.py
  tests/test_create.py
Labels: cla-signed

#13035 Speed up find_commands() on WSL
  conda/cli/find_commands.py
  news/13035-faster-find-commands
Labels: cla-signed

#13036 Fix `conda info --all`
  conda/cli/conda_argparse.py
  news/12985-verbosity
  tests/cli/test_main_info.py
  tests/test_info.py
Labels: cla-signed

#13034 Update requirements.txt
  news/13034-fix-test-data
  tests/conda_env/specs/test_requirements.py
  tests/conda_env/support/requirements.txt
Labels: cla-signed

#11610 check if directory is writable
  conda_env/installers/pip.py
  news/11610-check-permissions-directory
Labels: source::anaconda, cla-signed, stale::recovered

#10841 Catch a write permission errors when creating the package cache directory
  conda/core/package_cache_data.py
  news/9609-catch-NotWritableError
Labels: cla-signed, stale::recovered

#13048 Extract static pytest args into config
  .github/codecov.yml
  .github/workflows/tests.yml
  .gitignore
  .pre-commit-config.yaml
  conda-forge.yml
  dev/linux/integration.sh
  dev/linux/qemu.sh
  dev/linux/unit.sh
  dev/macos/integration.sh
  dev/macos/unit.sh
  dev/windows/integration.bat
  dev/windows/unit.bat
  pyproject.toml
  setup.cfg
  tests/cli/test_main_search.py
  tests/requirements.txt
Labels: cla-signed

#13044 Disallow ability to create a conda env with `:` in the prefix
  conda/cli/install.py
  news/12749-no-colon-in-prefix
  tests/conda_env/test_create.py
Labels: cla-signed

#13050 configuring retry behavior to ignore "retry-after" headers
  conda/gateways/connection/session.py
  news/13050-ignore-retry-after-header
Labels: cla-signed
