Repository conda/conda, pull requests merged in 2023-01, with the labels that each got.

#12003 Add a repodata gateway, refactoring existing code
  conda/core/subdir_data.py
  conda/exceptions.py
  conda/gateways/repodata/__init__.py
  news/12003-repodata-gateway
  tests/core/test_subdir_data.py
  tests/test_create.py
  tests/test_fetch.py
Labels: source::anaconda, cla-signed, sprint

#12213 Document channel::package syntax for environment.yml files
  docs/source/user-guide/tasks/manage-environments.rst
  news/11890-env-yml-channel-pkg-docs
Labels: cla-signed

#12218 Update release process to include creating a version on RTD.
  RELEASE.md
Labels: cla-signed

#12099 Fix More Crashes in MatchSpec and Version Parsing
  conda/common/url.py
  conda/models/match_spec.py
  conda/models/version.py
  keep_branch_open
  news/12099-fix-fuzzing-crashes
  tests/models/test_match_spec.py
  tests/models/test_version.py
Labels: cla-signed, sprint

#12230 Updating docs to remove references to the mythical version 5 🦄
  docs/source/user-guide/tasks/manage-channels.rst
Labels: source::anaconda, cla-signed, type::documentation

#11667 Detect CUDA driver version in subprocess
  conda/plugins/virtual_packages/cuda.py
  news/11667-cuda-detect-in-subprocess
Labels: source::community, cla-signed

#12233 lock stdout while writing json progress bar
  conda/common/io.py
  news/12231-lock-json-output
Labels: cla-signed

#12251 correct test recipe
  tests/test-recipes/activate_deactivate_package/meta.yaml
Labels: cla-signed

#12249 Release 23.1.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/11667-cuda-detect-in-subprocess
  news/11738-update-tab-completion-docs
  news/11890-env-yml-channel-pkg-docs
  news/11949-fix-behavior-of-no-user-flag-in-conda-init
  news/12003-repodata-gateway
  news/12099-fix-fuzzing-crashes
  news/12128-avoid-warning-when-env-vars-same-value-as-os-values
  news/12164-concat-itertools
  news/12165-tlz-unique
  news/12231-lock-json-output
Labels: source::anaconda, cla-signed

#12254 Remove `OrderedDict`/`odict`
  conda/base/context.py
  conda/cli/main_info.py
  conda/common/_os/linux.py
  conda/common/compat.py
  conda/common/configuration.py
  conda/common/pkg_formats/python.py
  conda/common/serialize.py
  conda/core/link.py
  conda/core/prefix_data.py
  conda/core/solve.py
  conda/gateways/connection/session.py
  conda/models/channel.py
  conda/models/prefix_graph.py
  conda/resolve.py
  conda/testing/fixtures.py
  conda/testing/solver_helpers.py
  conda_env/env.py
  news/12254-remove-odict
  tests/base/test_context.py
  tests/common/pkg_formats/test_python.py
  tests/common/test_configuration.py
  tests/conda_env/test_cli.py
  tests/conda_env/test_env.py
  tests/core/test_prefix_data.py
  tests/models/test_channel.py
  tests/test_activate.py
  tests/test_api.py
  tests/test_resolve.py
Labels: source::anaconda, cla-signed

#12257 use context.subdir to get current platform for virtual packages
  conda/plugins/virtual_packages/archspec.py
  conda/plugins/virtual_packages/linux.py
  conda/plugins/virtual_packages/osx.py
  conda/plugins/virtual_packages/windows.py
  news/12219-virtual-packages
  tests/plugins/test_virtual_packages.py
Labels: cla-signed

#12253 Replace `toolz.itertoolz.interleave` with `zip`
  conda/core/link.py
  tests/common/test_iterators.py
Labels: source::anaconda, cla-signed

#12252 Implement custom `unique` function
  conda/base/context.py
  conda/common/configuration.py
  conda/common/iterators.py
  conda_env/env.py
  news/12252-custom-unique-implementation
Labels: source::anaconda, cla-signed

#12201 Honor `Exception.allow_retry` in `PackagesNotFoundError` too
  conda/cli/install.py
  news/12201-exception-allow-retry
Labels: source::partner, cla-signed

#12262 Add .jlap, .json.zst extensions to paths to make them downloadable
  conda/common/path.py
  news/12261-add-downloadable-extensions
Labels: cla-signed

#12271 modify test to account for boltons in defaults
  tests/test_create.py
Labels: cla-signed, sprint

#12039 Remove `toolz.dicttoolz.merge(_with)` usage
  conda/common/configuration.py
  news/12039-stop-using-toolz.dicttoolz.merge
  tests/common/test_iterators.py
  tests/core/test_path_actions.py
Labels: source::anaconda, cla-signed

#12050 Defer list of PackageRecord objects
  .github/workflows/tests.yml
  conda/core/subdir_data.py
  conda/testing/helpers.py
  news/12268-packagerecord-list
  tests/requirements.txt
Labels: source::anaconda, cla-signed, sprint

#12239 Adds a new config parameter: `channel_settings`
  conda/base/context.py
  conda/cli/main_config.py
  news/12239-add-channel-settings-parameter
  tests/base/test_context.py
Labels: type::feature, source::anaconda, cla-signed

#12293 yield libc virtual package only if libc_version is truthy
  conda/plugins/virtual_packages/linux.py
  news/12267-conda-override-glibc
  tests/plugins/test_virtual_packages.py
Labels: cla-signed

#11915 fixed errors when renaming without an active env
  conda/base/context.py
  conda/cli/common.py
  news/11915-no-active-env-renaming-error
  tests/cli/test_common.py
Labels: source::community, cli, cla-signed
