Repository conda/conda, pull requests merged in 2023-07, with the labels that each got.

#12841 Add `conda env` CLI docs
  .gitignore
  conda/plugins/subcommands/doctor/cli.py
  docs/source/commands/doctor.rst
  docs/source/commands/env/config/index.rst
  docs/source/commands/env/config/vars/index.rst
  docs/source/commands/env/config/vars/list.rst
  docs/source/commands/env/config/vars/set.rst
  docs/source/commands/env/config/vars/unset.rst
  docs/source/commands/env/create.rst
  docs/source/commands/env/export.rst
  docs/source/commands/env/index.rst
  docs/source/commands/env/list.rst
  docs/source/commands/env/remove.rst
  docs/source/commands/env/update.rst
  docs/source/commands/index.rst
  news/12841-add-conda-env-cli-docs
Labels: cla-signed

#12757 Add "detect altered packages" health check
  conda/plugins/subcommands/doctor/health_checks.py
  news/12757-add-detect-altered-packages-health-check
  tests/plugins/subcommands/doctor/test_cli.py
  tests/plugins/subcommands/doctor/test_health_checks.py
Labels: source::anaconda, cla-signed, plugins

#12863 Add advisory for Miniconda pkg installers
  docs/source/user-guide/install/macos.rst
Labels: cla-signed, type::documentation

#12865 Fix SyntaxError in canary CI step.
  .github/workflows/tests.yml
Labels: cla-signed

#12867 Revert `tests.yml` syntax changes in favor of using Python 3.11
  .github/workflows/tests.yml
Labels: cla-signed

#12871 docs: non-URL channels can be organizations
  docs/source/user-guide/configuration/use-condarc.rst
Labels: cla-signed

#12874 Add (back) `cygpath` fallback
  conda/activate.py
  news/12874-cygpath-fallback
  tests/core/test_initialize.py
Labels: cla-signed

#12875 Release 23.5.1
  .authors.yml
  CHANGELOG.md
  news/12874-cygpath-fallback
Labels: source::anaconda, cla-signed

#12877 Bump conda/actions to 23.7.0
  .github/workflows/builds-review.yaml
  .github/workflows/tests.yml
Labels: cla-signed

#12880 `native_path_to_unix` needs to handle empty strings and empty iterables
  conda/activate.py
  news/12880-correct-native_path_to_unix
  tests/test_activate.py
Labels: cla-signed

#12882 Merge 23.5.x back into main (via bridge)
  .authors.yml
  CHANGELOG.md
  conda/activate.py
  tests/core/test_initialize.py
  tests/test_activate.py
Labels: cla-signed

#12864 Remove arguments/`sys.argv` from pre/post_command actions
  conda/cli/conda_argparse.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/plugins/types.py
  conda_env/cli/main.py
  docs/source/dev-guide/plugins/post_commands.rst
  docs/source/dev-guide/plugins/pre_commands.rst
  news/12712-pre-command-plugin-hook
  news/12758-post-command-plugin-hook
  tests/plugins/test_post_command.py
  tests/plugins/test_pre_command.py
Labels: cla-signed

#12869 Modify plugin loading to only use canonical names
  conda/plugins/manager.py
  news/12869-canonical-names
  tests/plugins/data/test-plugin/test_plugin-1.0.dist-info/entry_points.txt
  tests/plugins/data/test-plugin/test_plugin/blocked.py
  tests/plugins/data/test-plugin/test_plugin/importerror.py
  tests/plugins/data/test-plugin/test_plugin/success.py
  tests/plugins/test_manager.py
Labels: cla-signed

#12887 Build ePub, PDF and HTML zip formats as well.
  .readthedocs.yml
Labels: cla-signed

#12824 Create a `--no-plugins` option to disable external conda plugins
  conda/base/constants.py
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/main.py
  conda/exception_handler.py
  conda/plugins/manager.py
  news/12824-disable-plugins
  tests/plugins/__init__.py
  tests/plugins/test_manager.py
Labels: cla-signed

#12814 Revise subcommand plugin hook API
  conda/cli/conda_argparse.py
  conda/plugins/subcommands/doctor/cli.py
  conda/plugins/subcommands/doctor/health_checks.py
  conda/plugins/types.py
  conda_env/cli/main.py
  docs/source/commands/doctor.rst
  news/12814-revise-subcommand-hook
  tests/plugins/conftest.py
  tests/plugins/test_subcommands.py
Labels: cla-signed

#12879 Convert `test-recipes` into local noarch packages
  .gitpod.yml
  dev/linux/integration.sh
  dev/macos/integration.sh
  dev/windows/integration.bat
  news/12879-convert-test-recipes-noarch
  tests/cli/test_cli_install.py
  tests/conftest.py
  tests/requirements.txt
  tests/test-recipes/activate_deactivate_package/meta.yaml
  tests/test-recipes/b_post_link_package/meta.yaml
  tests/test-recipes/c_post_link_package/meta.yaml
  tests/test-recipes/d_post_link_package/meta.yaml
  tests/test-recipes/e_post_link_package/meta.yaml
  tests/test-recipes/noarch/.gitignore
  tests/test-recipes/noarch/activate_deactivate_package-1.0.0-0.tar.bz2
  tests/test-recipes/noarch/b_post_link_package-1.0.0-0.tar.bz2
  tests/test-recipes/noarch/c_post_link_package-1.0.0-0.tar.bz2
  tests/test-recipes/noarch/d_post_link_package-1.0.0-0.tar.bz2
  tests/test-recipes/noarch/e_post_link_package-1.0.0-0.tar.bz2
  tests/test-recipes/noarch/pre_link_messages_package-1.0.0-0.tar.bz2
  tests/test-recipes/noarch/repodata.json
  tests/test-recipes/noarch/repodata.json.bz2
  tests/test-recipes/pre_link_messages_package/meta.yaml
  tests/test_activate.py
  tests/test_create.py
  tests/test_link_order.py
Labels: cla-signed

#12862 Add conda_cli test for `conda doctor`
  tests/cli/test_subcommands.py
Labels: cla-signed

#12893 Deduplicate plugin and legacy subcommands
  conda/cli/conda_argparse.py
  news/12893-deduplicate-subcommands
Labels: cla-signed

#12890 Build ePub, PDF and HTML zip formats as well.
  .readthedocs.yml
Labels: cla-signed

#12897 Remove unused docs dependency
  docs/requirements.txt
Labels: cla-signed

#12900 Remove unused PyYAML dependency
  docs/requirements.txt
Labels: cla-signed

#12899 Remove unused PyYAML dependency
  docs/requirements.txt
Labels: cla-signed

#12904 Move plugin disabling into argument parser initialization.
  .pre-commit-config.yaml
  conda/cli/conda_argparse.py
  conda/exception_handler.py
  conda/plugins/manager.py
  tests/plugins/test_manager.py
  tests/plugins/test_subcommands.py
Labels: cla-signed

#12811 Optimize conda_initialize_content for fish-shell, improve the 400x speed
  conda/core/initialize.py
  news/12811-optimize-fish-initialization
Labels: cla-signed

#12895 Parametrize `test_priority.py`
  tests/test_priority.py
Labels: cla-signed

#12914 lazy-load boto3 to save ~400ms startup time
  conda/gateways/connection/adapters/s3.py
  news/lazy-load-boto3
Labels: cla-signed

#12901 Release 23.7.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/12493-add-conda.deprecations.DeprecationHandler.action
  news/12517-update-test_main_rename
  news/12647-add-freebsd-support
  news/12683-fix-jsondecode-error
  news/12696-do-not-set-context-CONDA_PREFIX
  news/12701-deprecate-context-root_dir
  news/12707-sha256-matchspec
  news/12712-pre-command-plugin-hook
  news/12715-osx-virtual-package
  news/12725-deprecate-get_prefix
  news/12735-deprecate-leased-path-entry-type
  news/12757-add-detect-altered-packages-health-check
  news/12758-post-command-plugin-hook
  news/12762-distutils-deprecation
  news/12769-fix-bug-deactivation
  news/12781-add-citation-file
  news/12792-adds-all-module-docstrings
  news/12795-deprecate-temporary_content_in_file
  news/12796-deprecate-python_api
  news/12798-add-sphinx-autoapi
  news/12802-revise-plugins-index-page
  news/12813-reenable-conda_env-tests
  news/12814-revise-subcommand-hook
  news/12819-convert-all-unittests-to-pytests
  news/12824-disable-plugins
  news/12841-add-conda-env-cli-docs
  news/12869-canonical-names
  news/12879-convert-test-recipes-noarch
  news/12893-deduplicate-subcommands
  news/12910-two-phase-parser
Labels: source::anaconda, cla-signed

#12919 replace inspect.stack() with sys._getframe() to save ~170ms -> ~90ms
  conda/deprecations.py
  news/sys-getframe-inspect-stack
Labels: cla-signed

#12922 Update conda recipe file
  recipe/meta.yaml
Labels: cla-signed

#12929 Patch 2-phase parser to preserve `pre_args`
  conda/cli/conda_argparse.py
  conda/cli/main.py
  conda/testing/__init__.py
  tests/cli/test_subcommands.py
Labels: cla-signed

#12930 Release 23.7.1
  .authors.yml
  .mailmap
  CHANGELOG.md
Labels: cla-signed

#12931 Merge `23.7.x` branch back into `main`
  .authors.yml
  .mailmap
  CHANGELOG.md
  conda/cli/conda_argparse.py
  conda/cli/main.py
  conda/testing/__init__.py
  tests/cli/test_subcommands.py
Labels: cla-signed

#12923 jlap: disable warning when not context.ssl_verify
  conda/gateways/repodata/jlap/interface.py
  news/12731-jlap-respect-ssl-verify
  tests/conftest.py
  tests/fixtures_jlap.py
  tests/gateways/test_jlap.py
Labels: cla-signed

#12932 Increase timeout for activation test on conda-forge.
  tests/test_activate.py
Labels: cla-signed

#12936 Do not parse unknowns, reparse entire args
  conda/cli/main.py
  news/12936-fix-parsing-json-debug-for-executable-subcommands
Labels: cla-signed

#12939 Release 23.7.2
  .authors.yml
  CHANGELOG.md
  news/12936-fix-parsing-json-debug-for-executable-subcommands
Labels: cla-signed

#12927 remove cache_path_* arguments
  conda/gateways/repodata/__init__.py
  conda/gateways/repodata/jlap/interface.py
  news/12927-remove-unused-cache-path-arguments
Labels: cla-signed

#12941 Merge `23.7.x` branch back into `main`
  .authors.yml
  CHANGELOG.md
  conda/cli/main.py
Labels: cla-signed
