Repository conda/conda, pull requests merged in 2023-02, with the labels that each got.

#12125 Implement `conda.deprecations.deprecated` decorator
  conda/__init__.py
  conda/__version__.py
  conda/_vendor/toolz/__init__.py
  conda/_vendor/tqdm/__init__.py
  conda/auxlib/decorators.py
  conda/base/context.py
  conda/cli/common.py
  conda/cli/conda_argparse.py
  conda/common/cuda.py
  conda/common/path.py
  conda/common/url.py
  conda/core/index.py
  conda/core/solve.py
  conda/deprecations.py
  conda/exceptions.py
  conda/exports.py
  conda/lock.py
  conda_env/cli/common.py
  news/12125-added-conda.deprecations.deprecated
  recipe/meta.yaml
  tests/requirements.txt
  tests/test_deprecations.py
Labels: source::anaconda, cla-signed

#12302 cache minio for windows
  .github/workflows/tests.yml
  dev/windows/setup.bat
Labels: source::anaconda, cla-signed

#12311 improve windows development setup script
  dev/start.bat
  news/12311-improve-start-bat
Labels: cla-signed

#11883 Fix confusing error message for env create with missing file
  conda_env/cli/main_create.py
  conda_env/cli/main_update.py
  conda_env/specs/__init__.py
  tests/conda_env/test_cli.py
Labels: cla-signed

#12320 miscellaneous test improvements
  tests/models/test_channel.py
  tests/notices/test_fetch.py
Labels: cla-signed

#12328 Remove accidentally added file.
  keep_branch_open
Labels: cla-signed

#12319 Add support for the 64-bit RISC-V architecture on Linux
  conda/_vendor/cpuinfo/__init__.py
  conda/_vendor/cpuinfo/cpuinfo.py
  conda/_vendor/py_cpuinfo.LICENSE
  conda/_vendor/vendor.txt
  conda/base/constants.py
  conda/base/context.py
  conda/models/enums.py
  news/12319-add-support-for-64-bit-riscv
Labels: source::anaconda, cla-signed

#12309 remove check for conda-build that doesn't understand .conda
  conda/base/context.py
  news/12309-conda-build-conda
  recipe/meta.yaml
Labels: source::anaconda, cla-signed, sprint

#12312 Channel Notices doesn't handle i/o errors
  conda/cli/main_notices.py
  conda/notices/cache.py
  conda/notices/core.py
  tests/cli/test_main_notices.py
Labels: source::anaconda, cla-signed

#12315 remove unused _track_features_index optimization
  conda/core/subdir_data.py
  news/remove-track-features-index
  tests/core/test_subdir_data.py
Labels: source::anaconda, cla-signed, sprint

#12331 Tests to improve coverage of repodata gateway, subdir_data
  conda/common/compat.py
  conda/common/serialize.py
  conda/gateways/disk/create.py
  news/12231-skip-chown-root-linux
  tests/core/test_package_cache_data.py
  tests/core/test_subdir_data.py
  tests/gateways/test_repodata_gateway.py
Labels: cla-signed, sprint

#12304 12275 conda docs package search specification
  docs/source/img/conda_search.png
  docs/source/user-guide/concepts/index.rst
  docs/source/user-guide/concepts/pkg-search.rst
  docs/source/user-guide/tasks/manage-environments.rst
  news/12275-conda-docs-package-search-specification
Labels: source::anaconda, cla-signed

#12335 Build Docker images with conda-forge base too
  .github/workflows/images.yml
  Dockerfile
  dev/linux/bashrc.sh
  dev/linux/install_miniconda.sh
  dev/linux/integration.sh
  dev/linux/setup.sh
  dev/linux/unit.sh
  docker-compose.yml
  docs/source/dev-guide/development-environment.md
  news/12335-conda-forge-docker-image
Labels: cla-signed

#12341 test filtering viewed notices
  tests/notices/test_core.py
  tests/test_plan.py
Labels: cla-signed

#12344 Xonsh: allow --help and --version passthrough in conda.xsh
  conda/shell/conda.xsh
  news/12344-passthrough-version-help-xonsh
Labels: cla-signed

#12354 improve reliability of test_prefix_graph
  tests/models/test_prefix_graph.py
Labels: cla-signed

#12074 add environment variable expansion for repository url
  conda_env/env.py
  news/10018-add-environment-variable-expansion-for-repository-url
  tests/conda_env/support/channels_with_envvars.yml
  tests/conda_env/test_env.py
Labels: cla-signed, pending::support

#12350 Add support for a `conda-forge`-based CI
  .github/workflows/tests.yml
  conda/testing/__init__.py
  dev/linux/integration.sh
  dev/linux/unit.sh
  dev/macos/integration.sh
  dev/macos/setup.sh
  dev/macos/unit.sh
  news/12350-conda-forge-ci
  tests/test_activate.py
  tests/test_cli.py
  tests/test_create.py
  tests/test_info.py
  tests/test_priority.py
Labels: cla-signed

#12363 Removed instances of `NotebookSpec` from __init__.py file
  conda_env/specs/__init__.py
  conda_env/specs/notebook.py
  news/12363-remove-notebook-spec-support-deprecated
  tests/conda_env/specs/test_notebook.py
Labels: cla-signed

#12378 Add info about `conda remove -n <env-name> --all` in conda CLI help
  conda/cli/conda_argparse.py
  news/12378-add-info-about-conda-remove-in-conda-CLI-help
Labels: cla-signed

#12395 Create embedded links on docs pages
  docs/source/user-guide/concepts/channels.rst
  docs/source/user-guide/tasks/manage-channels.rst
Labels: source::anaconda, cla-signed, type::documentation, sprint

#12297 Tune OSX test splits
  .github/workflows/tests.yml
  .test_durations_Linux
  .test_durations_Windows
  .test_durations_macOS
  conda/testing/__init__.py
  conda/testing/helpers.py
  dev/linux/integration.sh
  dev/linux/unit.sh
  dev/macos/integration.sh
  dev/macos/setup.sh
  dev/macos/unit.sh
  dev/windows/integration.bat
  dev/windows/unit.bat
  tests/combine_durations.py
  tests/test_create.py
  tests/test_misc.py
  tests/test_resolve.py
Labels: source::anaconda, cla-signed

#12412 simple lint fixes pointed out by ruff
  tests/cli/test_config.py
  tests/cli/test_main_notices.py
  tests/core/test_subdir_data.py
  tests/test_activate.py
  tests/test_cli.py
  tests/test_misc.py
Labels: cla-signed
