Repository conda/conda, pull requests merged in 2023-10, with the labels that each got.

#13166 Add sort check for requirements.txt files
  .pre-commit-config.yaml
  tests/requirements-extra.txt
  tests/requirements.txt
Labels: cla-signed

#13169 Correct github id for Travis E. Oliphant
  .authors.yml
Labels: cla-signed

#13177 constrain conda-build >=3.27
  news/13177-minimum-conda-build
  recipe/meta.yaml
Labels: cla-signed

#13197 Addressing flaky `pexpect` parsing
  tests/test_activate.py
Labels: cla-signed

#13170 Cleanup dependencies
  conda/testing/gateways/fixtures.py
  dev/linux/integration.sh
  dev/macos/setup.sh
  dev/start
  dev/start.bat
  dev/windows/setup.bat
  pyproject.toml
  recipe/meta.yaml
  tests/cli/test_main_search.py
  tests/requirements-Windows.txt
  tests/requirements-s3.txt
  tests/requirements.txt
Labels: cla-signed

#13194 Deprecate `conda.exports.fetch_index`
  conda/exports.py
  news/13194-deprecate-fetch_index
Labels: cla-signed

#13193 Deprecate `conda.models.dist.IndexRecord`
  conda/exports.py
  conda/models/dist.py
  conda/models/match_spec.py
  news/13193-deprecate-IndexRecord
  tests/test_plan.py
Labels: cla-signed

#11794 Provide `--platform` / `--subdir` flag to create (and remember) an environment for a platform different than native
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/cli/install.py
  conda_env/cli/main_create.py
  news/11794-platform-flag
  tests/test_create.py
Labels: source::partner, cla-signed

#13208 check symlink, not target name for condarc
  conda/common/configuration.py
  news/12956-check-condarc-without-resolving-symlink
  tests/common/test_configuration.py
Labels: cla-signed

#13210 Quieter jlap error handling after range request.
  conda/gateways/repodata/jlap/fetch.py
  news/12913-expected-jlap-error-handling
  tests/gateways/test_jlap.py
Labels: cla-signed

#13085 test_connection: use lighter-weight mock to test s3:// channels
  news/13085-lightweight-s3-mock
  tests/cli/test_main_search.py
  tests/data/conda_format_repo/linux-64/current_repodata.json
  tests/gateways/test_connection.py
Labels: cla-signed

#13218 remove ruamel_yaml import/except fallback
  conda/common/configuration.py
  conda/common/serialize.py
  news/drop-ruamel-underscore-yaml
Labels: cla-signed

#13224 Fixed typo in CONTRIBUTING.md CHANGELOG.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: cla-signed

#13220 update plugins documentation
  docs/source/dev-guide/plugins/index.rst
Labels: source::anaconda, cla-signed, documentation::reference

#13232 Fix for `conda --debug` error
  conda/cli/conda_argparse.py
  news/13232-option-parsing-bugfix
  tests/cli/test_main.py
Labels: cla-signed

#13191 Add (de)activate to --help command list
  conda/cli/conda_argparse.py
  conda/cli/main_mock_activate.py
  conda/cli/main_mock_deactivate.py
  news/13191-add-activate-to-help
  tests/test_activate.py
Labels: type::feature, source::community, cla-signed

#13173 Inline imports in `conda.cli.main_*` and break up `conda.cli.conda_argparse`
  conda/base/constants.py
  conda/cli/actions.py
  conda/cli/conda_argparse.py
  conda/cli/helpers.py
  conda/cli/main_clean.py
  conda/cli/main_compare.py
  conda/cli/main_config.py
  conda/cli/main_create.py
  conda/cli/main_info.py
  conda/cli/main_init.py
  conda/cli/main_install.py
  conda/cli/main_list.py
  conda/cli/main_mock_activate.py
  conda/cli/main_mock_deactivate.py
  conda/cli/main_notices.py
  conda/cli/main_package.py
  conda/cli/main_pip.py
  conda/cli/main_remove.py
  conda/cli/main_rename.py
  conda/cli/main_run.py
  conda/cli/main_search.py
  conda/cli/main_update.py
  conda_env/cli/main_list.py
  pyproject.toml
  tests/cli/test_conda_argparse.py
  tests/cli/test_main_notices.py
  tests/cli/test_main_rename.py
Labels: cla-signed

#13239 Add news file for PR 13173
  news/13173-conda-cli-and-argparse-updates
Labels: source::anaconda, cla-signed

#12984 Make conda-libmamba-solver the default solver
  conda/base/constants.py
  conda/plugins/subcommands/doctor/health_checks.py
  conda/testing/fixtures.py
  conda/testing/helpers.py
  dev/linux/integration.sh
  dev/linux/unit.sh
  dev/macos/setup.sh
  dev/windows/setup.bat
  docs/source/dev-guide/deep-dives/install.md
  docs/source/dev-guide/deep-dives/solvers.md
  news/12984-conda-libmamba-solver-default
  pyproject.toml
  recipe/meta.yaml
  tests/cli/test_cli_install.py
  tests/cli/test_main_notices.py
  tests/cli/test_main_search.py
  tests/cli/test_subcommands.py
  tests/conda_env/test_cli.py
  tests/core/test_solve.py
  tests/models/test_prefix_graph.py
  tests/plugins/test_solvers.py
  tests/requirements.txt
  tests/test_create.py
  tests/test_export.py
  tests/test_priority.py
  tests/test_solvers.py
Labels: cla-signed

#13213 Add archspec dependency
  conda/core/index.py
  recipe/meta.yaml
  tests/requirements.txt
Labels: cla-signed

#13231 Resume downloads / refactor download() function
  conda/gateways/connection/download.py
  conda/gateways/disk/lock.py
  conda/gateways/repodata/__init__.py
  conda/gateways/repodata/lock.py
  news/8695-resume-downloads
  tests/test_fetch.py
Labels: cla-signed

#13249 sort package downloads by size descending
  conda/core/package_cache_data.py
  news/13248-sort-packages-descending
Labels: cla-signed

#13171 Remove imports from pip/requests's vendored packages
  conda/base/context.py
  conda/cli/main_info.py
  conda/common/compat.py
  news/13171-charset-normalizer
  pyproject.toml
  recipe/meta.yaml
  tests/requirements.txt
Labels: cla-signed

#13261 Release 23.10.0
  .authors.yml
  CHANGELOG.md
  news/11794-platform-flag
  news/12956-check-condarc-without-resolving-symlink
  news/12984-conda-libmamba-solver-default
  news/13144-deprecate-generate_argparser
  news/13177-minimum-conda-build
  news/13193-deprecate-IndexRecord
  news/13194-deprecate-fetch_index
Labels: cla-signed

#13267 Fix typo in test_cli.py
  tests/conda_env/test_cli.py
Labels: cla-signed

#13263 Fix CONDA_FETCH_THREADS parameter
  conda/base/context.py
  news/context-fetch-threads
Labels: cla-signed
