Repository conda/conda, pull requests merged in 2023-09, with the labels that each got.

#13014 remove cgi import
  conda/gateways/connection/adapters/ftp.py
  news/13013-remove-cgi
Labels: cla-signed

#13065 Debugging recent failures in `test_main_clean.py`
  .github/workflows/tests.yml
  tests/cli/test_main_clean.py
Labels: cla-signed

#13076 Fix key sorting for `json.dumps` in `conda config`
  conda/cli/main_config.py
  news/13076-json-sort-pathlib
  tests/cli/test_main_config.py
Labels: cla-signed

#13071 use scandir() in find_commands.py to avoid stat() calls against 23.7.x branch
  conda/cli/find_commands.py
  news/find-commands-scandir
Labels: cla-signed

#13086 23.7.x find commands permission error
  conda/cli/find_commands.py
  news/13062-find-commands-permission-error
  tests/cli/test_find_commands.py
Labels: cla-signed

#13087 Fix context mocking for CondaSession test
  tests/gateways/test_connection.py
Labels: cla-signed

#13090 Backport test fixes to 23.7.x
  .github/workflows/tests.yml
  conda/testing/gateways/fixtures.py
  news/12986-fix-S3-bucket-name
Labels: cla-signed

#13088 [23.7.x backport] Fix key sorting for `json.dumps` in `conda config` (#13076)
  conda/cli/main_config.py
  news/13076-json-sort-pathlib
  tests/cli/test_main_config.py
Labels: cla-signed

#13089 Catch `NotADirectoryError`
  conda/cli/find_commands.py
  news/13062-find-commands-permission-error
  tests/cli/test_find_commands.py
Labels: cla-signed

#13094 Merge `23.7.x` branch back into `main`
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  conda/cli/find_commands.py
  tests/cli/test_find_commands.py
Labels: cla-signed

#13095 Add emscripten-wasm32 and wasi-wasm32 platforms to known platforms
  conda/base/constants.py
  news/13095-wasm-platforms
Labels: cla-signed

#13099 Install anaconda-client from conda-forge for tests
  tests/requirements.txt
Labels: cla-signed

#13021 Fix conda remove all json
  conda/cli/main_remove.py
  news/13019-conda-remove-all-json
  tests/cli/test_subcommands.py
Labels: cla-signed

#13101 catch JSONDecodeError when loading repodata cache metadata
  conda/gateways/repodata/__init__.py
  news/13056-jsondecodeerror
  tests/gateways/test_jlap.py
Labels: cla-signed

#13000 Add healthcheck for checking whether the environment is listed on environments.txt
  conda/plugins/subcommands/__init__.py
  conda/plugins/subcommands/doctor/__init__.py
  conda/plugins/subcommands/doctor/cli.py
  conda/plugins/subcommands/doctor/health_checks.py
  tests/plugins/subcommands/doctor/test_health_checks.py
Labels: cla-signed

#13057 Move all pluggy specifics into the manager
  conda/cli/conda_argparse.py
  conda/core/index.py
  conda/plugins/manager.py
  tests/plugins/conftest.py
  tests/plugins/test_manager.py
  tests/plugins/test_subcommands.py
Labels: cla-signed

#13074 Fix mistake in doc string
  conda/plugins/types.py
Labels: cla-signed

#13107 Add a py.typed marker
  conda/py.typed
  news/13107-add-py-typed-marker
Labels: cla-signed

#13111 reindex test repository, fixing checksums
  tests/data/conda_format_repo/linux-64/current_repodata.json
  tests/data/conda_format_repo/linux-64/repodata.json
  tests/data/conda_format_repo/osx-64/current_repodata.json
  tests/data/conda_format_repo/osx-64/repodata.json
  tests/data/conda_format_repo/win-32/current_repodata.json
  tests/data/conda_format_repo/win-32/repodata.json
  tests/data/conda_format_repo/win-64/current_repodata.json
  tests/data/conda_format_repo/win-64/repodata.json
Labels: cla-signed

#13112 remove code for unsupported boto library (boto3 remains)
  conda/gateways/connection/adapters/s3.py
  news/drop-boto2
Labels: cla-signed

#13119 clarify changelog
  CHANGELOG.md
Labels: cla-signed

#13108 prefer log.warning() in conda.gateways.repodata
  conda/gateways/repodata/__init__.py
  tests/gateways/test_jlap.py
Labels: cla-signed

#12279 Use ruff
  .pre-commit-config.yaml
  conda/cli/conda_argparse.py
  conda/common/compat.py
  conda/common/configuration.py
  conda/core/subdir_data.py
  conda/exceptions.py
  conda/exports.py
  conda/gateways/connection/__init__.py
  conda/testing/helpers.py
  news/12279-ruff
  pyproject.toml
  tests/cli/test_cli_install.py
  tests/cli/test_conda_argparse.py
  tests/cli/test_main_info.py
  tests/cli/test_main_run.py
  tests/cli/test_main_search.py
  tests/cli/test_subcommands.py
  tests/conda_env/test_create.py
  tests/conftest.py
  tests/core/test_initialize.py
  tests/core/test_subdir_data.py
  tests/gateways/disk/test_delete.py
  tests/gateways/test_repodata_gateway.py
  tests/plugins/data/test-plugin/test_plugin/importerror.py
  tests/plugins/subcommands/doctor/test_health_checks.py
  tests/requirements.txt
  tests/test_export.py
  tests/test_exports.py
  tests/test_link_order.py
  tests/test_priority.py
  tests/trust/test_signature_verification.py
Labels: source::anaconda, cla-signed

#13124 Show git diff after all pre-commit hooks to be able to see auto-format/fix changes
  .pre-commit-config.yaml
Labels: cla-signed

#13127 Catch OSError in find_commands
  conda/cli/find_commands.py
  news/13125-find_commands-catch-oserror
  tests/cli/test_find_commands.py
Labels: cla-signed

#13126 Lazily import boto3 within method
  conda/gateways/connection/__init__.py
  conda/gateways/connection/adapters/s3.py
Labels: cla-signed

#13075 Use OS Truststore in corporate HTTPS inspection proxies
  conda/base/context.py
  conda/gateways/connection/__init__.py
  conda/gateways/connection/adapters/http.py
  conda/gateways/connection/session.py
  docs/source/user-guide/troubleshooting.rst
  news/13075-ssl-verify-truststore
  pyproject.toml
  tests/cli/test_config.py
  tests/test_create.py
Labels: source::community, cla-signed

#13051 MatchSpec warning was missing the f-prefix for the string
  conda/models/match_spec.py
Labels: cla-signed

#13118 More refactoring for plugin manager.
  conda/plugins/manager.py
  tests/plugins/test_manager.py
  tests/plugins/test_subcommands.py
Labels: source::anaconda, cla-signed, plugins

#13084 Use `conda-forge::minio-server`
  .github/workflows/images.yml
  .github/workflows/tests.yml
  dev/linux/integration.sh
  dev/linux/qemu.sh
  dev/linux/setup.sh
  dev/macos/setup.sh
  dev/windows/setup.bat
  tests/requirements-extra.txt
  tests/requirements.txt
Labels: cla-signed

#13012 Source bash files in non-interactive mode
  conda/activate.py
  news/13012-dont-source-interactive
  tests/test_activate.py
Labels: cla-signed

#13141 Update recipe metadata dependencies
  LICENSE
  news/12948-removals
  pyproject.toml
  recipe/meta.yaml
  tests/common/test_iterators.py
  tests/core/test_path_actions.py
  tests/requirements.txt
Labels: cla-signed

#13151 Log missing or non-string RepodataState items at debug level instead …
  conda/gateways/repodata/__init__.py
Labels: cla-signed

#13153 Changelog 23.9.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/11610-check-permissions-directory
  news/12279-ruff
  news/12731-jlap-respect-ssl-verify
  news/12749-no-colon-in-prefix
  news/12811-optimize-fish-initialization
  news/12889-trust-metadata-fetch-auth
  news/12911-auth-handler-plugin-hook
  news/12920-lock-default
  news/12924-context-register-envs
  news/12927-remove-unused-cache-path-arguments
  news/12948-removals
  news/12966-jlap-file-uri
  news/12982-no-progress-bars-in-logs
  news/12985-verbosity
  news/12986-fix-S3-bucket-name
  news/12988-CONDA_JSON
  news/13012-dont-source-interactive
  news/13013-remove-cgi
  news/13019-conda-remove-all-json
  news/13034-fix-test-data
  news/13035-faster-find-commands
  news/13050-ignore-retry-after-header
  news/13056-jsondecodeerror
  news/13075-ssl-verify-truststore
  news/13076-json-sort-pathlib
  news/13095-wasm-platforms
  news/13107-add-py-typed-marker
  news/13125-find_commands-catch-oserror
  news/9609-catch-NotWritableError
  news/9614-prune-ignores-history-specs
  news/drop-boto2
  news/lazy-load-boto3
  news/sys-getframe-inspect-stack
Labels: cla-signed

#13154 Clarify content of $CONDARC
  docs/source/user-guide/configuration/use-condarc.rst
Labels: cla-signed

#13159 Fix CMD.exe activation test
  tests/test_activate.py
Labels: cla-signed

#13155 Merge 23.9.x back into main post-release.
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  conda/gateways/repodata/__init__.py
  news/11610-check-permissions-directory
  news/12279-ruff
  news/12731-jlap-respect-ssl-verify
  news/12749-no-colon-in-prefix
  news/12811-optimize-fish-initialization
  news/12889-trust-metadata-fetch-auth
  news/12911-auth-handler-plugin-hook
  news/12920-lock-default
  news/12924-context-register-envs
  news/12927-remove-unused-cache-path-arguments
  news/12948-removals
  news/12966-jlap-file-uri
  news/12982-no-progress-bars-in-logs
  news/12985-verbosity
  news/12986-fix-S3-bucket-name
  news/12988-CONDA_JSON
  news/13012-dont-source-interactive
  news/13013-remove-cgi
  news/13019-conda-remove-all-json
  news/13034-fix-test-data
  news/13035-faster-find-commands
  news/13050-ignore-retry-after-header
  news/13056-jsondecodeerror
  news/13075-ssl-verify-truststore
  news/13076-json-sort-pathlib
  news/13095-wasm-platforms
  news/13107-add-py-typed-marker
  news/13125-find_commands-catch-oserror
  news/9609-catch-NotWritableError
  news/9614-prune-ignores-history-specs
  news/drop-boto2
  news/lazy-load-boto3
  news/sys-getframe-inspect-stack
  recipe/meta.yaml
  tests/test_activate.py
Labels: cla-signed

#13157 Only continue tests.yml workflow if not canceled
  .github/workflows/tests.yml
Labels: cla-signed

#13100 Minio no shadow variable
  conda/testing/gateways/fixtures.py
Labels: cla-signed

#13161 Enforce `on_linux`, `on_mac`, and `on_win` usage and remove some Python 2.7 code
  conda/cli/conda_argparse.py
  conda/common/_os/linux.py
  conda/core/portability.py
  conda/gateways/disk/create.py
  conda/misc.py
  conda/models/enums.py
  conda/testing/__init__.py
  tests/core/test_solve.py
  tests/gateways/test_repodata_lock.py
  tests/test_misc.py
Labels: cla-signed
