Repository conda/conda, pull requests merged in 2023-04, with the labels that each got.

#12509 Convert `setup.py` to `pyproject.toml` using hatch build system
  .git_archival.txt
  .gitattributes
  .gitignore
  LICENSE
  Makefile
  conda/__version__.py
  conda/auxlib/packaging.py
  conda/testing/__init__.py
  news/12509-hatchling-build-system
  pyproject.toml
  recipe/build.sh
  recipe/meta.yaml
  setup.py
  tests/__init__.py
  tests/requirements.txt
Labels: cla-signed

#12555 Use appropriate `defaults` value for Windows is use when subdir=win-*
  conda/base/context.py
  news/12555-defaults-win-subdir
Labels: os::windows, source::contributor, cla-signed

#12541 fallback when deprecations cannot read conda version
  conda/deprecations.py
  news/12541-deprecation-version-fallback
  tests/test_deprecations.py
Labels: cla-signed

#12492 Deprecate unused `conda_env` functions
  conda/cli/main_info.py
  conda_env/__init__.py
  conda_env/__main__.py
  conda_env/cli/main.py
  conda_env/env.py
  conda_env/pip_util.py
  news/12492-conda-env-deprecations
Labels: cla-signed

#12536 Ignore paths that cannot be stat-ed
  conda/cli/main_clean.py
  news/12536-fix-stat-unboundlocalerror
  tests/cli/test_main_clean.py
Labels: cla-signed

#12580 Create Python 3.11 image
  .github/workflows/images.yml
  tests/requirements.txt
Labels: cla-signed

#12588 Remove `CONDA_ENABLE_PRIVATE_ENVS` tests
  conda/cli/main_remove.py
  tests/test_create.py
Labels: cla-signed

#12565 defend against bad types in repodata state
  conda/core/subdir_data.py
  conda/gateways/repodata/__init__.py
  news/12562-cache-typeerror
  tests/gateways/test_repodata_gateway.py
Labels: cla-signed

#12124 Add doctor subcommand plugin
  conda/cli/conda_argparse.py
  conda/plugins/manager.py
  conda/plugins/subcommands/__init__.py
  conda/plugins/subcommands/doctor/__init__.py
  conda/plugins/subcommands/doctor/cli.py
  conda/plugins/subcommands/doctor/health_checks.py
  tests/plugins/subcommands/doctor/test_cli.py
  tests/plugins/subcommands/doctor/test_health_checks.py
Labels: source::anaconda, cla-signed, plugins

#12256 Python 3.11
  .github/workflows/tests.yml
  conda/cli/conda_argparse.py
  docs/source/dev-guide/development-environment.md
  docs/source/user-guide/tasks/manage-python.rst
  docs/source/user-guide/tasks/use-conda-with-travis-ci.rst
  news/12256-python-3.11
  pyproject.toml
  recipe/conda_build_config.yaml
  tests/test_create.py
Labels: source::community, cla-signed

#12603 Simplify recipe and add missing tests
  recipe/bld.bat
  recipe/build.sh
  recipe/meta.yaml
  recipe/run_test.bat
  recipe/run_test.sh
Labels: cla-signed

#12604 Fix UrlsData.get_url
  conda/core/package_cache_data.py
  news/12604-fix-urlsdata-get-url
  tests/core/test_package_cache_data.py
Labels: cla-signed

#12622 Enable canary builds for release branches
  .github/workflows/tests.yml
Labels: cla-signed

#12591 Add content trust root-related tests
  conda/trust/signature_verification.py
  tests/requirements.txt
  tests/trust/test_signature_verification.py
  tests/trust/testdata/1.root.json
  tests/trust/testdata/2.root.json
  tests/trust/testdata/2.root_invalid.json
  tests/trust/testdata/3.root.json
  tests/trust/testdata/3.root_invalid.json
  tests/trust/testdata/key_mgr.json
  tests/trust/testdata/key_mgr_invalid.json
  tests/trust/testdata/repodata_sample.json
  tests/trust/testdata/repodata_short_signed_sample.json
  tests/trust/testdata/test_key_1_268B62D0.pri.asc
  tests/trust/testdata/test_key_1_268B62D0.pub.asc
  tests/trust/testdata/test_key_2_7DB43643.pri.asc
  tests/trust/testdata/test_key_2_7DB43643.pub.asc
Labels: cla-signed
