Repository conda/conda, pull requests merged in 2023-05, with the labels that each got.

#12629 Ignore comment style D200
  setup.cfg
Labels: cla-signed

#12638 Adding Anaconda's conda basics course.
  docs/source/user-guide/index.rst
Labels: cla-signed, documentation::tutorials

#12639 Warn about misconfiguration when signature verification is enabled
  conda/trust/signature_verification.py
  news/12639-warn-missing-sig-url-base
Labels: cla-signed

#12419 Update manage-channels.rst channel_priority examples
  docs/source/user-guide/tasks/manage-channels.rst
Labels: cla-signed

#12612 Issue #12007: Change "failed" language to "unsuccessful attempt"
  conda/core/solve.py
  news/12007-fail-retry-language
Labels: source::community, cla-signed, documentation::explanation

#12583 Add docs about mirroring channels
  docs/source/user-guide/configuration/index.rst
  docs/source/user-guide/configuration/mirroring.rst
  news/12583-doc-mirror
Labels: source::contributor, cla-signed, documentation::explanation

#12641 Follow up #12583: fix broken references
  docs/source/dev-guide/deep-dives/solvers.md
  docs/source/user-guide/configuration/mirroring.rst
  news/12583-doc-mirror
Labels: cla-signed, documentation::explanation

#12627 Ensure all paths in `conda.sh` are prefix-replaceable on Windows
  conda/activate.py
  news/12627-fix-msys2-conda.sh-paths
  tests/core/test_initialize.py
Labels: source::anaconda, cla-signed

#12656 Update deprecation version to reflect when function was deprecated
  conda/core/subdir_data.py
Labels: cla-signed

#12661 Correct the deprecation versions on `read_mod_and_etag()` function
  conda/core/subdir_data.py
Labels: source::anaconda, type::task, cla-signed

#12672 Remove potential `test_confirm_*` uncertainty with `always_yes` being set
  tests/cli/test_common.py
Labels: cla-signed

#12670 rename `.state.json` to `.info.json` to track draft CEP
  conda/core/subdir_data.py
  conda/gateways/repodata/__init__.py
  conda/gateways/repodata/jlap/fetch.py
  news/12669-parametrize-cache-keys
  tests/gateways/test_jlap.py
  tests/gateways/test_repodata_gateway.py
Labels: cla-signed

#12550 Optimize imports for `conda activate` calls
  conda/activate.py
  conda/cli/main.py
  conda/common/io.py
  conda/common/path.py
  conda/deprecations.py
  conda/exception_handler.py
  conda/exceptions.py
  conda/gateways/disk/delete.py
  conda/testing/gateways/fixtures.py
  conda/testing/integration.py
  conda/utils.py
  news/12550-optimize-activate-imports
  tests/test_activate.py
  tests/test_exceptions.py
  tests/test_utils.py
Labels: source::contributor, tag::performance, cla-signed

#12673 name hash algorithm in keys to better track draft CEP
  conda/gateways/repodata/jlap/fetch.py
Labels: cla-signed

#12592 Introducing `conda_cli`, `tmp_env`, and `path_factory` fixtures
  conda/cli/main_info.py
  conda/cli/main_remove.py
  conda/cli/main_run.py
  conda/testing/__init__.py
  conda/testing/helpers.py
  conda/testing/integration.py
  docs/source/dev-guide/writing-tests/integration-tests.md
  news/12592-conda_cli-fixture
  tests/cli/test_subcommands.py
  tests/conftest.py
  tests/test_create.py
Labels: source::anaconda, cla-signed

#12679 `conda.testing.run` was renamed to `conda.testing.conda_cli`
  conda/testing/helpers.py
  conda/testing/integration.py
Labels: cla-signed

#12676 Deprecate `conda.testing.integration.get_conda_list_tuple`
  conda/testing/integration.py
  news/12676-deprecate-get_conda_list_tuple
  tests/test_priority.py
Labels: cla-signed

#12678 Deprecate `conda.testing.integration.temp_chdir`
  conda/testing/integration.py
  news/12678-deprecate-temp_chdir
Labels: cla-signed

#12677 Deprecate `conda.testing.encode_for_env_var`
  conda/testing/__init__.py
  news/12677-deprecate-encode_for_env_var
Labels: cla-signed

#12475 Add improved repo/cache interface, polish jlap feature (#12474)
  conda/core/subdir_data.py
  conda/gateways/repodata/__init__.py
  conda/gateways/repodata/jlap/fetch.py
  conda/gateways/repodata/jlap/interface.py
  conda/testing/fixtures.py
  news/12521-jlap-improvements
  tests/core/test_subdir_data.py
  tests/gateways/test_jlap.py
  tests/gateways/test_repodata_gateway.py
Labels: source::anaconda, cla-signed

#12687 Always build canary when pushed to main/feature/release
  .github/workflows/tests.yml
Labels: cla-signed

#12691 Add missing `f` for fstring and update imports
  conda/gateways/repodata/__init__.py
Labels: source::anaconda, cla-signed

#12690 remove cache_dir memoization to improve unit tests reliability
  .github/workflows/tests.yml
  conda/core/subdir_data.py
Labels: cla-signed

#12685 Release 23.5.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/12007-fail-retry-language
  news/12256-python-3.11
  news/12492-conda-env-deprecations
  news/12509-hatchling-build-system
  news/12521-jlap-improvements
  news/12536-fix-stat-unboundlocalerror
  news/12541-deprecation-version-fallback
  news/12550-optimize-activate-imports
  news/12554-auto-format
  news/12555-defaults-win-subdir
  news/12562-cache-typeerror
  news/12579-update-readme-example
  news/12583-doc-mirror
  news/12592-conda_cli-fixture
  news/12604-fix-urlsdata-get-url
  news/12620-add-flake8-docstrings
  news/12627-fix-msys2-conda.sh-paths
  news/12639-warn-missing-sig-url-base
  news/12669-parametrize-cache-keys
  news/12676-deprecate-get_conda_list_tuple
  news/12677-deprecate-encode_for_env_var
  news/12678-deprecate-temp_chdir
  news/gh-11954-list-reverse
Labels: cla-signed

#12688 Convert `test_history.py` to pytest-style
  tests/test_history.py
Labels: cla-signed

#12682 Convert `tests/test_create.py` to pytest-style
  tests/test_create.py
Labels: cla-signed

#12708 Fix hatch-vcs error in canary builds
  pyproject.toml
  recipe/meta.yaml
Labels: cla-signed

#12647 Add support for x86-64 FreeBSD
  conda/base/constants.py
  conda/base/context.py
  conda/models/enums.py
  conda/plugins/virtual_packages/__init__.py
  conda/plugins/virtual_packages/freebsd.py
  news/12647-add-freebsd-support
Labels: source::anaconda, cla-signed

#12517 Remove `test_main_rename.py` customizations in favor of existing functions/fixtures
  news/12517-update-test_main_rename
  tests/cli/test_main_rename.py
Labels: source::anaconda, cla-signed

#11740 Add conda binary to $PATH first before initialize.
  docs/source/user-guide/install/linux.rst
Labels: source::community, cla-signed

#12715 Do not yield osx virtual package when CONDA_OVERRIDE_OSX=""
  conda/plugins/virtual_packages/osx.py
  news/12715-osx-virtual-package
  tests/plugins/test_virtual_packages.py
Labels: cla-signed
