Repository conda/conda, pull requests merged in 2023-03, with the labels that each got.

#12411 Move durations into tests directory.
  .github/workflows/tests.yml
  dev/linux/integration.sh
  dev/linux/unit.sh
  dev/macos/integration.sh
  dev/macos/unit.sh
  dev/windows/integration.bat
  dev/windows/unit.bat
  tests/durations/Linux.json
  tests/durations/Windows.json
  tests/durations/combine.py
  tests/durations/macOS.json
Labels: cla-signed

#12389 Sync package subdir with repodata subdir
  news/12389-sync-repodata-fix
  tests/data/conda_format_repo/win-64/current_repodata.json
  tests/data/conda_format_repo/win-64/repodata.json
Labels: cla-signed, type::testing

#12413 use 2 unit test splits for osx, to reduce concurrency
  .github/workflows/tests.yml
  tests/test_resolve.py
Labels: cla-signed

#12416 Various Sphinx/docs fixes.
  .readthedocs.yml
  docs/source/_ext/conda_umls.py
Labels: cla-signed

#12423 Build UML files on RTD separately.
  .readthedocs.yml
  docs/source/_ext/conda_umls.py
Labels: cla-signed

#12353 add note to exception if 'use_only_tar_bz2' is enabled
  conda/exceptions.py
  news/12353-use-only-tar-bz2-hint
  tests/test_exceptions.py
Labels: source::partner, cla-signed

#12428 Reformat news snippet filename and content
  news/12315-remove-track-features-index
Labels: source::anaconda, type::task, cla-signed

#12432 remove --cov-report term-missing from setup.cfg
  setup.cfg
Labels: cla-signed

#12398 Mark some code in `context.py` and `cli/main_info.py` for official deprecation
  conda/base/context.py
  conda/cli/main_info.py
  conda/gateways/connection/adapters/s3.py
  news/12276-context-and-cli-deprecations
  news/12398-context-and-cli-deprecations
  tests/test_create.py
Labels: source::anaconda, type::task, cla-signed, sprint

#12424 miscellaneous refactors originating from features/repodata-jlap
  conda/core/subdir_data.py
  tests/conftest.py
  tests/core/test_subdir_data.py
  tests/gateways/test_repodata_gateway.py
  tests/http_test_server.py
  tests/test_create.py
  tests/test_resolve.py
Labels: cla-signed

#12446 Init conda after installing requirements in tests
  dev/linux/unit.sh
  news/12446-init-conda-after-installing-requirements
Labels: cla-signed

#12450 Remove libmamba issue template
  .github/ISSUE_TEMPLATE/3_libmamba-solver-feedback.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed

#12448 Remove defaults from command line in Linux unit tests
  dev/linux/unit.sh
  news/12350-conda-forge-ci
Labels: cla-signed

#12439 Removing Python 3.7 from matrix. Also, making exclude matrix on linu…
  .github/workflows/images.yml
  .github/workflows/tests.yml
Labels: cla-signed

#12453 Mark `conda._vendor.boltons` for deprecation.
  .github/workflows/tests.yml
  conda/_vendor/boltons/__init__.py
  conda/auxlib/entity.py
  conda/base/context.py
  conda/cli/main_search.py
  conda/common/configuration.py
  conda/core/index.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/models/channel.py
  conda/models/prefix_graph.py
  conda/models/records.py
  conda/plan.py
  conda_env/installers/conda.py
  dev/linux/install_miniconda.sh
  dev/linux/qemu.sh
  dev/linux/setup.sh
  news/12272-mark-vendor-boltons-for-deprecation
  recipe/meta.yaml
  tests/requirements.txt
Labels: cla-signed

#12457 improve test coverage of conda.common.configuration
  conda/common/configuration.py
  tests/common/test_configuration.py
Labels: cla-signed

#12466 Speedup pre-commit by factor 15
  .pre-commit-config.yaml
  news/12466-speedup-pre-commit
Labels: cla-signed

#12469 Trivial coverage improvements
  conda/base/constants.py
  conda/core/initialize.py
  tests/models/test_prefix_graph.py
  tests/notices/test_core.py
Labels: cla-signed

#12468 Ignore `PYTHONPATH` when updating `devenv`
  dev/start
Labels: cla-signed

#12090 features/repodata jlap
  conda/base/context.py
  conda/cli/conda_argparse.py
  conda/core/subdir_data.py
  conda/gateways/repodata/__init__.py
  conda/gateways/repodata/jlap/core.py
  conda/gateways/repodata/jlap/fetch.py
  conda/gateways/repodata/jlap/interface.py
  conda/gateways/repodata/lock.py
  dev/windows/setup.bat
  news/12090-repodata-jlap
  news/12268-default-no-coverage
  news/repodata-cache-format
  setup.cfg
  tests/conftest.py
  tests/core/test_subdir_data.py
  tests/fixtures_jlap.py
  tests/gateways/test_jlap.py
  tests/gateways/test_repodata_gateway.py
  tests/gateways/test_repodata_lock.py
  tests/requirements.txt
Labels: source::anaconda, cla-signed

#12460 Handle ImportError gracefully while loading plugins.
  conda/plugins/manager.py
  news/12460-handle-plugins-importerror
  setup.cfg
  tests/plugins/data/test-plugin/test_plugin-1.0.dist-info/METADATA
  tests/plugins/data/test-plugin/test_plugin-1.0.dist-info/entry_points.txt
  tests/plugins/data/test-plugin/test_plugin/__init__.py
  tests/plugins/data/test-plugin/test_plugin/plugin.py
  tests/plugins/test_manager.py
Labels: cla-signed

#12470 Tweaks for dropping Python 3.7 support.
  conda/cli/conda_argparse.py
  news/12436-drop-37-support
  setup.py
  tests/cli/test_cli_install.py
  tests/test_create.py
Labels: cla-signed

#12482 Change how `IndexedSet` is asserted
  conda/core/solve.py
  conda/core/subdir_data.py
  news/12272-mark-vendor-boltons-for-deprecation
Labels: cla-signed

#12452 Deprecation docs
  docs/source/dev-guide/deprecations.md
  docs/source/dev-guide/index.rst
  news/12125-added-conda.deprecations.deprecated
Labels: source::anaconda, cla-signed

#12480 Fix typo in recipe.
  recipe/meta.yaml
Labels: cla-signed

#12487 catch `ChunkedEncodingError` too
  conda/gateways/connection/__init__.py
  conda/gateways/repodata/__init__.py
  news/12487-ChunkedEncodingError
Labels: cla-signed

#12490 catch and ignore existence errors in `mkdir_p_sudo_safe`
  conda/gateways/disk/__init__.py
  news/12490-mkdir-p-sudo-safe-race
Labels: cla-signed

#12486 Release 23.3.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/10018-add-environment-variable-expansion-for-repository-url
  news/11915-no-active-env-renaming-error
  news/12039-stop-using-toolz.dicttoolz.merge
  news/12090-repodata-jlap
  news/12125-added-conda.deprecations.deprecated
  news/12201-exception-allow-retry
  news/12219-virtual-packages
  news/12231-skip-chown-root-linux
  news/12238-anaconda-cloud-needs-changed-to-anacondaorg-in-docs
  news/12239-add-channel-settings-parameter
  news/12252-custom-unique-implementation
  news/12254-remove-odict
  news/12261-add-downloadable-extensions
  news/12267-conda-override-glibc
  news/12268-default-no-coverage
  news/12268-packagerecord-list
  news/12272-mark-vendor-boltons-for-deprecation
  news/12275-conda-docs-package-search-specification
  news/12276-context-and-cli-deprecations
  news/12285-improve-plugin-subcommand-arg-parsing
  news/12294-ruff-fixes
  news/12309-conda-build-conda
  news/12311-improve-start-bat
  news/12315-remove-track-features-index
  news/12319-add-support-for-64-bit-riscv
  news/12335-conda-forge-docker-image
  news/12344-passthrough-version-help-xonsh
  news/12345-bugfix-for-list-all-known-prefixes
  news/12350-conda-forge-ci
  news/12353-use-only-tar-bz2-hint
  news/12363-remove-notebook-spec-support-deprecated
  news/12378-add-info-about-conda-remove-in-conda-CLI-help
  news/12389-sync-repodata-fix
  news/12398-context-and-cli-deprecations
  news/12414-deprecate-hashsum_file
  news/12415-deprecate-safe_open
  news/12436-drop-37-support
  news/12446-init-conda-after-installing-requirements
  news/12460-handle-plugins-importerror
  news/12466-speedup-pre-commit
  news/12487-ChunkedEncodingError
  news/12490-mkdir-p-sudo-safe-race
  news/repodata-cache-format
Labels: cla-signed

#12497 Drop Python 3.7 canary build
  recipe/conda_build_config.yaml
Labels: cla-signed

#12498 Add s390x to multi-arch container
  .github/workflows/images.yml
  news/12498-s390x-container
Labels: cla-signed

#12510 Remove Python version pinning for correct test results
  tests/test_create.py
Labels: cla-signed

#12511 Coverage tests for conda list, etc.
  conda/auxlib/entity.py
  conda/base/context.py
  conda/common/configuration.py
  conda/core/index.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/gateways/disk/link.py
  conda/instructions.py
  conda/lock.py
  conda/models/channel.py
  conda/models/prefix_graph.py
  conda/models/records.py
  conda/plan.py
  conda_env/installers/conda.py
  tests/cli/test_conda_argparse.py
  tests/core/test_package_cache_data.py
  tests/test_instructions.py
  tests/test_toposort.py
Labels: cla-signed

#12504 Make split line f-string
  conda/gateways/repodata/jlap/fetch.py
Labels: cla-signed

#12513 Restore default argument for `SubdirData` method used by `conda-index`.
  conda/core/subdir_data.py
  news/conda-index-fix
Labels: cla-signed

#12495 Update & reenable binstar tests
  conda_env/specs/binstar.py
  news/12495-reenable-binstar-tests
  setup.cfg
  tests/conda_env/specs/test_binstar.py
Labels: cla-signed

#12523 Test that cache revalidate updates ttl
  tests/gateways/test_jlap.py
Labels: cla-signed

#12524 Provide a way to pin `minio` in CI
  .github/workflows/tests.yml
  dev/linux/setup.sh
  dev/macos/setup.sh
  dev/windows/setup.bat
  news/12524-minio-pin
Labels: cla-signed

#12529 Install missing curl for Linux images
  .github/workflows/images.yml
  dev/linux/setup.sh
Labels: cla-signed

#12545 add __init__.py for conda.gateways.repodata.jlap
  conda/gateways/repodata/jlap/__init__.py
Labels: cla-signed

#12533 Add help text for --file flag for the `conda env export` command
  conda_env/cli/main_export.py
Labels: source::anaconda, cli, cla-signed
