Repository conda/conda, pull requests merged in 2024-02, with the labels that each got.

#13551 add zstandard as a run dependency
  docs/source/user-guide/concepts/conda-plugins.rst
  pyproject.toml
  recipe/meta.yaml
Labels: cla-signed

#13556 Fix conda pre, post and health check plugin examples
  conda/plugins/hookspec.py
Labels: cla-signed

#13553 Modernise tests in `test_create.py`
  tests/test_create.py
Labels: cla-signed

#13555 Remove `--no-test` from canary builds
  .github/workflows/builds-review.yaml
  .github/workflows/tests.yml
Labels: cla-signed

#13546 Refactor rollback tests, move `conda run` test, and refactor revisions test
  tests/cli/test_main_run.py
  tests/test_create.py
Labels: cla-signed

#13565 Enable `conda rename` to not throw a `TypeError` when conda is not activated
  conda/cli/main_rename.py
  news/13565-conda-can-rename-while-inactive
Labels: type::bug, source::anaconda, cla-signed

#13537 Refactor pip interoperability tests
  tests/test_create.py
Labels: cla-signed

#13572 Updating Miniconda links
  HOW_WE_USE_GITHUB.md
  README.md
  docs/requirements.txt
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/user-guide/getting-started.rst
  docs/source/user-guide/install/index.rst
  docs/source/user-guide/install/linux.rst
  docs/source/user-guide/install/macos.rst
  docs/source/user-guide/install/windows.rst
  docs/source/user-guide/troubleshooting.rst
  news/13572-conda-sphinx-docs-version-0-2-1
Labels: cla-signed

#13543 Channel IDs not parsed as strings
  conda/notices/types.py
  news/13543-bugfix-for-channel-notice-integer-message-id
  tests/notices/test_types.py
Labels: cla-signed

#13582 Ruff has moved some of the config values
  pyproject.toml
Labels: cla-signed

#13568 Optimize import time for `conda activate`
  conda/auxlib/compat.py
  conda/base/context.py
  conda/cli/main.py
  conda/common/constants.py
  conda/deprecations.py
  conda/gateways/logging.py
  news/13568-import-activate-perf
  tests/test_deprecations.py
Labels: cla-signed

#13559 Catch ZstdError in jlap/repodata.json.zst handling
  conda/gateways/repodata/jlap/fetch.py
  news/13558-bad-zst-fallback
  tests/core/test_solve.py
  tests/gateways/test_jlap.py
Labels: cla-signed

#13576 change retry logic for 400 <= status < 500
  conda/gateways/repodata/jlap/fetch.py
  news/13573-skip-zst-on-4xx
Labels: cla-signed

#13532 Pass traceback, not str, to exception formatter.
  conda/exception_handler.py
  news/13531-keyboardinterrupt-traceback
Labels: cla-signed, in-progress

#13579 Add wildcard `conda remove` test
  tests/cli/test_main_remove.py
Labels: cla-signed

#13587 Add `ISC`/`TCH`/`T10`/`FA` lints
  conda/activate.py
  conda/cli/helpers.py
  conda/cli/main_clean.py
  conda/cli/main_compare.py
  conda/cli/main_env.py
  conda/cli/main_info.py
  conda/cli/main_init.py
  conda/cli/main_rename.py
  conda/cli/main_search.py
  conda/common/configuration.py
  conda/common/iterators.py
  conda/common/path.py
  conda/core/initialize.py
  conda/core/link.py
  conda/core/package_cache_data.py
  conda/core/solve.py
  conda/core/subdir_data.py
  conda/env/specs/binstar.py
  conda/exceptions.py
  conda/gateways/connection/adapters/s3.py
  conda/gateways/connection/session.py
  conda/gateways/disk/create.py
  conda/gateways/disk/read.py
  conda/gateways/repodata/__init__.py
  conda/gateways/repodata/jlap/core.py
  conda/gateways/repodata/jlap/fetch.py
  conda/gateways/repodata/jlap/interface.py
  conda/notices/cache.py
  conda/notices/core.py
  conda/notices/fetch.py
  conda/notices/types.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/plugins/subcommands/doctor/__init__.py
  conda/plugins/subcommands/doctor/health_checks.py
  conda/plugins/types.py
  conda/testing/__init__.py
  conda/testing/fixtures.py
  conda/testing/integration.py
  conda/testing/notices/helpers.py
  conda/trust/signature_verification.py
  conda/utils.py
  pyproject.toml
  tests/cli/test_main_clean.py
  tests/cli/test_main_rename.py
  tests/cli/test_subcommands.py
  tests/common/test_url.py
  tests/gateways/test_repodata_gateway.py
  tests/plugins/subcommands/doctor/test_health_checks.py
  tests/plugins/test_subcommands.py
  tests/plugins/test_virtual_packages.py
  tests/test_activate.py
  tests/test_history.py
  tests/trust/test_signature_verification.py
  tests/trust/testdata/keys/generate
  tools/durations/combine.py
Labels: cla-signed

#13588 Port `ZstdError` & HTTP 400-500 to `24.1.x`
  conda/gateways/repodata/jlap/fetch.py
  news/13558-bad-zst-fallback
  news/13573-skip-zst-on-4xx
  tests/core/test_solve.py
  tests/gateways/test_jlap.py
Labels: cla-signed

#13590 Release 24.1.1
  .authors.yml
  AUTHORS.md
  CHANGELOG.md
  docs/source/user-guide/concepts/conda-plugins.rst
  news/13558-bad-zst-fallback
  news/13573-skip-zst-on-4xx
Labels: cla-signed

#13596 Repair deprecated fetch repodata
  conda/core/subdir_data.py
  news/fetch-repodata-remote-request
  tests/core/test_subdir_data.py
Labels: cla-signed

#13597 Ignore `TYPE_CHECKING` imports in coverage reports
  pyproject.toml
Labels: cla-signed

#13606 Merge `24.1.x` back into `main`
  .authors.yml
  CHANGELOG.md
  conda/core/subdir_data.py
  tests/core/test_subdir_data.py
Labels: cla-signed

#13613 Update testing entrypoint deprecation
  conda/shell/bin/conda
Labels: cla-signed

#13618 Update all actions including setup-miniconda to their latest version
  .github/workflows/tests.yml
Labels: cla-signed

#13240 gateways.subprocess: fix subprocess_call when stdin is bytes
  conda/cli/python_api.py
  conda/common/compat.py
  conda/gateways/subprocess.py
  conda/testing/helpers.py
  conda/testing/integration.py
  news/13240-subprocess_call-text
  tests/gateways/test_subprocess.py
Labels: cla-signed

#13617 Run macos tests on osx-64 and osx-arm64 runners
  .github/workflows/tests.yml
  news/13617-enable-osx-arm64-tests
  tests/cli/test_main_info.py
  tests/test_activate.py
  tests/test_create.py
Labels: cla-signed

#13629 Remove `conda.export.handle_proxy_407`
  conda/exports.py
  news/13629-remove-handle_proxy_407
Labels: source::anaconda, cla-signed, type::deprecation

#13128 Add response string to repodata JSONDecodeError
  conda/gateways/repodata/__init__.py
  news/11804-annotate-jsondecodeerror
  tests/gateways/test_repodata_gateway.py
Labels: cla-signed

#13632 Fix `conda env create` "`--subdir` / `--platform`" flag regression
  conda/cli/main_env_create.py
  news/13632-fix-conda-env-create-subdir-platform-regression
Labels: type::bug, source::anaconda, cla-signed

#13611 Report progress while installing from --revision
  conda/cli/install.py
  news/13611-report-revisions
Labels: cla-signed

#13628 Fix auxlib.logz.stringify excess memory allocation
  conda/auxlib/logz.py
  news/13628-fix-auxlib-stringify-contenxt_max_len
Labels: cla-signed

#13577 Move `conda env export` to `conda export`
  conda/cli/conda_argparse.py
  conda/cli/main_env.py
  conda/cli/main_env_export.py
  conda/cli/main_export.py
  conda/env/env.py
  conda_env/cli/main_export.py
  news/13577-conda-export-command
  tests/cli/test_main_export.py
  tests/env/utils.py
  tests/test_conda_env.py
Labels: type::task, cla-signed
