Repository conda/conda, pull requests merged in 2024-05, with the labels that each got.

#13869 Stop importing from `conda/exports.py`
  conda/plan.py
  news/13869-remove-imports-from-exports-module
  tests/core/test_package_cache_data.py
  tests/core/test_subdir_data.py
  tests/test_instructions.py
  tests/test_plan.py
Labels: cla-signed

#13881 Deprecate `conda.plan`
  conda/cli/install.py
  conda/misc.py
  conda/plan.py
  news/12421-deprecate-conda.plan
  tests/test_plan.py
Labels: cla-signed

#13884 Removing remaining usage of deprecated `make_temp_env`
  tests/core/test_subdir_data.py
  tests/gateways/test_connection.py
  tests/test_create.py
Labels: cla-signed

#13877 Small typo fix
  conda/cli/main_remove.py
Labels: cla-signed

#13885 Fix `conda info --all` tests to reflect deprecation
  tests/cli/test_main_info.py
  tests/conftest.py
Labels: cla-signed

#13888 `24.5.x`-related updates / corrections
  conda/gateways/logging.py
  news/13684-remove-setuptools-remainings
  news/13732-log-trace
  news/13801-deprecate-make_immutable
Labels: source::anaconda, type::task, cla-signed

#13889 Update conda cheatsheet text
  docs/source/user-guide/cheatsheet.rst
  docs/source/user-guide/cheatsheets/additional-hints.csv
  docs/source/user-guide/cheatsheets/channels-and-packages.csv
  docs/source/user-guide/cheatsheets/conda-4.12.pdf
  docs/source/user-guide/cheatsheets/conda-4.14.pdf
  docs/source/user-guide/cheatsheets/conda-4.6.pdf
  docs/source/user-guide/cheatsheets/environment-management.csv
  docs/source/user-guide/cheatsheets/exporting-environments.csv
  docs/source/user-guide/cheatsheets/importing-environments.csv
  docs/source/user-guide/cheatsheets/quickstart.csv
  docs/source/user-guide/cheatsheets/working-with-environments.csv
  news/13889-update-cheatsheet-text
Labels: cla-signed

#13886 Refactor `main_config` into a modular API
  conda/cli/install.py
  conda/cli/main_config.py
  conda/exceptions.py
  tests/cli/test_config.py
  tests/cli/test_main_config.py
Labels: cla-signed

#13649 support multiple MSYS2 environments
  conda/activate.py
  docs/source/user-guide/troubleshooting.rst
  news/13649-msys2-environments
  tests/test_activate.py
Labels: cla-signed

#13906 Changelog 24.5.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/12421-deprecate-conda.plan
  news/13437-conda-core-index-hints
  news/13598-matchspec-errors
  news/13649-msys2-environments
  news/13684-remove-setuptools-remainings
  news/13689-install-win-on-unix
  news/13720-deprecate-activate-testing-helpers
  news/13732-log-trace
  news/13736-add-reporters-setting
  news/13744-base-url
  news/13751-deprecate-mkdir
  news/13766-devendor-frozendict
  news/13779-channel-settings-url-wildcard
  news/13801-deprecate-make_immutable
  news/13869-remove-imports-from-exports-module
Labels: cla-signed

#13910 Remove `reporters` from 24.5.0 changelog
  CHANGELOG.md
  news/13736-reporters
Labels: cla-signed

#13911 Merge `24.5.x` back into `main`
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  conda/cli/install.py
  conda/cli/main_config.py
  conda/exceptions.py
  conda/gateways/logging.py
  conda/misc.py
  conda/plan.py
  news/13437-conda-core-index-hints
  news/13598-matchspec-errors
  news/13684-remove-setuptools-remainings
  news/13689-install-win-on-unix
  news/13720-deprecate-activate-testing-helpers
  news/13732-log-trace
  news/13736-add-reporters-setting
  news/13736-reporters
  news/13744-base-url
  news/13751-deprecate-mkdir
  news/13779-channel-settings-url-wildcard
  news/13801-deprecate-make_immutable
  tests/cli/test_config.py
  tests/cli/test_main_config.py
  tests/cli/test_main_info.py
  tests/conftest.py
  tests/core/test_package_cache_data.py
  tests/core/test_subdir_data.py
  tests/gateways/test_connection.py
  tests/test_create.py
  tests/test_instructions.py
  tests/test_plan.py
Labels: cla-signed

#13909 Added cheatsheet PDF download to cheatsheet page
  docs/source/user-guide/cheatsheet.rst
  docs/source/user-guide/cheatsheets/conda-24.4.0.pdf
  docs/source/user-guide/cheatsheets/conda-4.12.pdf
  docs/source/user-guide/cheatsheets/conda-4.14.pdf
  docs/source/user-guide/cheatsheets/conda-4.6.pdf
  docs/source/user-guide/conda-cheatsheet.pdf
  news/13909-add-cheatsheet-pdf
Labels: cla-signed

#13935 Document ssl_verify: truststore
  docs/source/user-guide/configuration/settings.rst
  news/13935-doc-truststore
Labels: cla-signed

#13950 Add docs on error handling for plugins
  docs/source/dev-guide/plugins/index.rst
  news/13950-doc-plugin-errors
Labels: cla-signed, type::documentation

#13941 Do not require name or prefix if we are running `create` with dry-run
  conda/base/constants.py
  conda/cli/main_create.py
  news/13941-dry-run-name
  tests/test_create.py
Labels: cla-signed

#13931 [conda doctor] Don't display `.pyc` and `.pyo` files in "missing files" health check
  conda/plugins/subcommands/doctor/health_checks.py
  news/13931-no-add-pyc-doctor
  tests/plugins/subcommands/doctor/test_health_checks.py
Labels: cla-signed
