Repository conda/conda, pull requests merged in 2024-08, with the labels that each got.

#14068 Move `path_identity` to `conda.common.path`
  conda/activate.py
  conda/common/path.py
  conda/utils.py
  news/14068-path-identity
  tests/common/test_path.py
  tests/test_activate.py
  tests/test_utils.py
Labels: cla-signed

#14115 Update `anaconda.org/conda-test` token
  tests/cli/test_main_search.py
Labels: cla-signed

#14098 `test_exceptions.py`: Replace `env_var` with `monkeypatch.setenv`
  tests/test_exceptions.py
Labels: cla-signed

#14116 Sync `conda.deprecations` with `conda_build.deprecations`
  conda/deprecations.py
Labels: cla-signed

#14118 Fix `conda.exports.move_to_trash` import
  conda/exports.py
  news/14118-deprecate-conda.exports.move_to_trash
  tests/test_exports.py
Labels: cla-signed

#14077 24.9 Removals
  LICENSE
  conda/_vendor/appdirs.LICENSE.txt
  conda/_vendor/appdirs.py
  conda/_vendor/cpuinfo/__init__.py
  conda/_vendor/cpuinfo/cpuinfo.py
  conda/_vendor/distro.LICENSE.txt
  conda/_vendor/distro.py
  conda/_vendor/py_cpuinfo.LICENSE
  conda/_vendor/vendor.txt
  conda/auxlib/collection.py
  conda/auxlib/compat.py
  conda/auxlib/exceptions.py
  conda/auxlib/type_coercion.py
  conda/base/context.py
  conda/base/exceptions.py
  conda/cli/main.py
  conda/cli/main_rename.py
  conda/cli/python_api.py
  conda/common/configuration.py
  conda/common/decorators.py
  conda/common/disk.py
  conda/core/package_cache.py
  conda/core/package_cache_data.py
  conda/core/prefix_data.py
  conda/core/subdir_data.py
  conda/exports.py
  conda/gateways/anaconda_client.py
  conda/gateways/connection/adapters/ftp.py
  conda/gateways/logging.py
  conda/models/dist.py
  conda/models/enums.py
  conda/models/leased_path_entry.py
  conda/notices/cache.py
  conda/plugins/subcommands/doctor/__init__.py
  conda/plugins/subcommands/doctor/health_checks.py
  conda/testing/helpers.py
  news/14077-24.7-removals
  pyproject.toml
  tests/common/test_configuration.py
  tests/core/test_package_cache_data.py
  tests/env/utils.py
  tests/plugins/subcommands/doctor/test_health_checks.py
  tests/test_exports.py
  tests/test_install.py
Labels: cla-signed

#14130 Add missing import in tests/envs/utils.py
  tests/env/utils.py
Labels: cla-signed

#14138 Add `platformdirs` to host section in recipe to fix canary builds
  recipe/meta.yaml
Labels: cla-signed

#14140 Remove remnants of old durations workflow
  .github/workflows/tests.yml
  durations/Linux.json
  durations/Windows.json
  durations/macOS.json
  tools/durations/Linux.json
  tools/durations/Windows.json
  tools/durations/combine.py
  tools/durations/macOS.json
Labels: cla-signed

#13955 Prevent protected directory paths from being able to be overridden as a conda environment prefix
  conda/cli/install.py
  conda/cli/main_create.py
  conda/cli/main_env_create.py
  conda/cli/main_rename.py
  news/13955-protected-dirs
  tests/cli/test_main_install.py
  tests/cli/test_main_rename.py
  tests/env/test_create.py
  tests/test_install.py
Labels: type::bug, source::anaconda, type::tech-debt, cla-signed

#14112 Make `conda doctor` first check if the specified environment exists or not
  conda/plugins/subcommands/doctor/__init__.py
  news/14112-env-exists-check
  tests/plugins/subcommands/doctor/test_cli.py
Labels: cla-signed

#14141 Move `conda/shell` tests into new `tests/test_shell.py`
  tests/test_activate.py
  tests/test_shell.py
Labels: cla-signed

#14144 Deprecate unused compat functions
  conda/activate.py
  conda/base/constants.py
  conda/common/compat.py
  conda/common/io.py
  news/14144-deprecate-unused-compat
  tests/common/test_compat.py
  tests/test_activate.py
Labels: cla-signed

#14149 Bug fix for `ObjectParameter` defaults
  conda/common/configuration.py
  news/14149-fix-object-parameter-defaults
  tests/common/test_configuration.py
Labels: cla-signed

#14160 Deprecate `conda.env.specs.binstar`
  conda/cli/main_env_create.py
  conda/cli/main_env_update.py
  conda/env/specs/__init__.py
  conda/env/specs/binstar.py
  conda_env/specs/__init__.py
  news/14158-deprecate-binstar
  tests/cli/test_env.py
  tests/env/specs/test_binstar.py
  tests/test_conda_env.py
Labels: cla-signed

#14163 Fix miniconda downloading in `. ./dev/start`
  dev/start
Labels: cla-signed

#14166 `test_main_info.py`: Replace `env_var` with `monkeypatch.setenv`
  tests/cli/test_main_info.py
Labels: cla-signed

#14162 Make version number dynamic for "Getting started" guide
  docs/source/user-guide/getting-started.rst
Labels: cla-signed

#14173 Fix `test_env_export_json` test and update `main_remove.py` to not delete parent empty directories
  conda/cli/main_remove.py
  news/14173-update-main-remove-and-env-export-test
  tests/cli/test_env.py
Labels: cla-signed

#14169 Adjust `conda.common.compat.open` deprecation
  conda/activate.py
  conda/common/compat.py
  conda/common/pkg_formats/python.py
  conda/core/envs_manager.py
  conda/core/initialize.py
  conda/gateways/disk/read.py
  conda/history.py
  conda/misc.py
  news/14144-deprecate-unused-compat
  tests/core/test_initialize.py
Labels: cla-signed

#14048 Add support for SHA256 hashes in explicit files
  conda/cli/main_list.py
  conda/misc.py
  news/14048-explicit-sha256
  tests/test_export.py
Labels: cla-signed

#14184 Remove unneeded distro.py patch.
  tools/vendoring/patches/distro.patch
Labels: cla-signed

#13977 Alias `conda env remove` command to `conda remove --all`
  conda/cli/main_env_remove.py
  news/13977-alias-conda-env-remove
  tests/cli/test_env.py
Labels: source::anaconda, type::tech-debt, cla-signed

#14189 Deprecate unused private env helper functions
  conda/common/path.py
  news/14189-deprecate-private-environment
Labels: cla-signed

#14192 Move `test_toposort.py` to `common/test_toposort.py`
  tests/common/test_toposort.py
Labels: cla-signed

#14191 Delete empty `test_file_permissions.py`
  tests/test_file_permissions.py
Labels: cla-signed

#14037 Add "requests_ca_bundle" health check to `conda doctor`
  conda/plugins/subcommands/doctor/health_checks.py
  news/14037-requests-ca-bundle-health-check
  tests/plugins/subcommands/doctor/test_health_checks.py
Labels: cla-signed

#14188 Deprecate `get_bin_directory_short_path()` in favor of `BIN_DIRECTORY`
  conda/base/context.py
  conda/common/path.py
  conda/core/initialize.py
  conda/core/link.py
  conda/core/path_actions.py
  conda/testing/integration.py
  news/14188-BIN_DIRECTORY
  tests/core/test_initialize.py
  tests/core/test_path_actions.py
  tests/test_create.py
Labels: cla-signed

#14194 Update `README.md` badges
  .github/workflows/tests.yml
  README.md
Labels: cla-signed

#14150 Reporter backends refactor
  conda/base/constants.py
  conda/base/context.py
  conda/cli/helpers.py
  conda/common/configuration.py
  conda/plugins/__init__.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/plugins/reporter_backends/console.py
  conda/plugins/reporter_backends/json.py
  conda/plugins/reporter_outputs/__init__.py
  conda/plugins/reporter_outputs/stdout.py
  conda/plugins/types.py
  conda/reporters.py
  docs/source/dev-guide/plugins/index.rst
  docs/source/dev-guide/plugins/reporter_backends.rst
  docs/source/dev-guide/plugins/reporter_outputs.rst
  tests/base/test_context.py
  tests/plugins/conftest.py
  tests/plugins/reporter_outputs/__init__.py
  tests/plugins/reporter_outputs/test_stdout.py
  tests/plugins/test_health_checks.py
  tests/plugins/test_post_commands.py
  tests/plugins/test_pre_commands.py
  tests/plugins/test_reporter_backends.py
  tests/plugins/test_reporter_outputs.py
  tests/test_reporters.py
Labels: cla-signed

#14195 Parameterize pip interop tests
  tests/common/pkg_formats/test_python.py
  tests/core/test_prefix_data.py
  tests/data/env_metadata/__init__.py
  tests/gateways/disk/test_read.py
Labels: cla-signed
