Repository conda/conda, pull requests merged in 2024-11, with the labels that each got.

#14362 Add two new tests for two functions in conda.base.context; improve coverage
  conda/cli/main_search.py
  tests/base/test_context.py
  tests/cli/test_main_search.py
Labels: source::anaconda, cla-signed

#14359 Update `deprecated.action()` to account for positional arguments with no value specified
  conda/deprecations.py
  news/14359-update-deprecated.action
  tests/test_deprecations.py
Labels: cla-signed

#14370 pre-commit.ci fixes
  conda/core/package_cache_data.py
  conda/plugins/types.py
  conda/reporters.py
  tests/test_reporters.py
Labels: cla-signed

#14371 More Python 3.8 Removals
  docs/source/dev-guide/plugins/index.rst
  docs/source/user-guide/install/index.rst
  docs/source/user-guide/tasks/manage-pkgs.rst
  docs/source/user-guide/tasks/manage-python.rst
  recipe/conda_build_config.yaml
  tests/requirements.txt
Labels: cla-signed

#14375 Fix `.coverage` upload to codecov.
  .github/workflows/tests.yml
  news/14375-fix-coverage-upload
Labels: cla-signed

#14256 Use `python_site_packages_path` when specified
  conda/core/link.py
  conda/core/prefix_data.py
  conda/models/records.py
  news/14053-cep-17
  tests/core/test_index.py
  tests/test-recipes/noarch/pip-99.99.99-py399_0.tar.bz2
  tests/test-recipes/noarch/python-3.99.99-0.tar.bz2
  tests/test-recipes/noarch/repodata.json
  tests/test-recipes/noarch/repodata.json.bz2
  tests/test-recipes/noarch/sample_noarch_python-1.0.0-py_0.tar.bz2
  tests/test-recipes/pip_py_3_99/meta.yaml
  tests/test-recipes/python_sp_path/meta.yaml
  tests/test-recipes/sample_noarch_python/meta.yaml
  tests/test_create.py
Labels: cla-signed

#14214 Fix typo in docs
  docs/source/dev-guide/deep-dives/install.md
Labels: cla-signed

#14245 Reporter backends plugin hook
  conda/base/constants.py
  conda/base/context.py
  conda/cli/common.py
  conda/cli/helpers.py
  conda/cli/install.py
  conda/cli/main_clean.py
  conda/cli/main_create.py
  conda/cli/main_info.py
  conda/cli/main_remove.py
  conda/cli/main_search.py
  conda/common/configuration.py
  conda/common/io.py
  conda/core/link.py
  conda/core/package_cache_data.py
  conda/core/solve.py
  conda/env/installers/pip.py
  conda/notices/fetch.py
  conda/plugins/__init__.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/plugins/reporter_backends/__init__.py
  conda/plugins/reporter_backends/console.py
  conda/plugins/reporter_backends/json.py
  conda/plugins/types.py
  conda/reporters.py
  docs/source/dev-guide/plugins/index.rst
  docs/source/dev-guide/plugins/reporter_backends.rst
  docs/source/user-guide/configuration/settings.rst
  news/13868-reporter-backend-and-reporter-output-plugin-hooks
  news/14083-progress-bar-support-reporter-backends
  news/14206-spinner-support-reporter-backends
  news/14244-confirm-support-reporter-backends
  tests/base/test_context.py
  tests/cli/test_common.py
  tests/cli/test_main_search.py
  tests/common/test_io.py
  tests/conftest.py
  tests/plugins/reporter_backends/__init__.py
  tests/plugins/reporter_backends/test_console.py
  tests/plugins/reporter_backends/test_json.py
  tests/plugins/test_health_checks.py
  tests/plugins/test_post_commands.py
  tests/plugins/test_post_solves.py
  tests/plugins/test_pre_commands.py
  tests/plugins/test_pre_solves.py
  tests/plugins/test_reporter_backends.py
  tests/test_reporters.py
Labels: source::anaconda, cla-signed, plugins

#14380 Improve caching on GHA Windows runners.
  .github/workflows/tests.yml
Labels: cla-signed

#14384 Remove pytest-codspeed install from personal fork
  .github/workflows/tests.yml
  tests/requirements-benchmarks.txt
Labels: cla-signed

#14382 Make request headers dynamic
  conda/gateways/connection/session.py
  conda/plugins/hookspec.py
  conda/plugins/manager.py
  conda/plugins/types.py
  docs/source/dev-guide/plugins/request_headers.rst
  news/14325-adding-request-headers-plugin-hook
  tests/gateways/test_connection.py
  tests/plugins/test_manager.py
  tests/plugins/test_request_headers.py
Labels: cla-signed

#14386 Add `yield from ()` to hookspecs to satisfy `mypy`
  conda/plugins/hookspec.py
Labels: cla-signed

#14387 Conditionally override version after cutting a release branch
  .github/workflows/tests.yml
  recipe/meta.yaml
Labels: cla-signed

#14390 Update `check_output()` call in `tests.yml`
  .github/workflows/tests.yml
Labels: cla-signed

#14396 Changelog 24.11.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/13784-conda-env-retry
  news/13868-reporter-backend-and-reporter-output-plugin-hooks
  news/14053-cep-17
  news/14083-progress-bar-support-reporter-backends
  news/14206-spinner-support-reporter-backends
  news/14244-confirm-support-reporter-backends
  news/14271-remove-createnonadmin-action
  news/14277-remove-__conda_reactivate-shell-function
  news/14317-pypi-names
  news/14323-fix-env-export-file-json
  news/14325-adding-request-headers-plugin-hook
  news/14338-deprecate-rel_path
  news/14359-update-deprecated.action
  news/14368-py38
  news/14375-fix-coverage-upload
Labels: cla-signed

#14398 Fixes bug for invalid arguments to `conda shell.posix` (and others)
  conda/activate.py
  news/14398-fix-invalid-args-error-message
  tests/test_activate.py
Labels: cla-signed

#14413 Ignore UP031.
  pyproject.toml
Labels: cla-signed

#14402 Sort subcommand choices on ArgumentError
  conda/cli/conda_argparse.py
  news/14402-sort-subcommands
  tests/cli/test_conda_argparse.py
Labels: cla-signed
