Repository conda/conda, pull requests merged in 2024-01, with the labels that each got.

#13450 Temporarily add `--no-test` to canary builds
  .github/workflows/builds-review.yaml
  .github/workflows/tests.yml
  dev/linux/integration.sh
  dev/linux/unit.sh
  dev/macos/setup.sh
  dev/windows/setup.bat
  pyproject.toml
  recipe/meta.yaml
  tests/requirements.txt
Labels: cla-signed

#13440 Warn user that `conda env remove` removes all contents of the prefix path
  conda/cli/main_remove.py
  news/13440-add-yn-prompt
  tests/cli/test_main_notices.py
Labels: cla-signed

#13474 More `test_create.py` refactoring!
  .pre-commit-config.yaml
  conda/testing/integration.py
  tests/test-recipes/dependent/meta.yaml
  tests/test-recipes/noarch/dependency-1.0-0.tar.bz2
  tests/test-recipes/noarch/dependency-2.0-0.tar.bz2
  tests/test-recipes/noarch/dependent-1.0-0.tar.bz2
  tests/test-recipes/noarch/dependent-2.0-0.tar.bz2
  tests/test-recipes/noarch/repodata.json
  tests/test-recipes/noarch/repodata.json.bz2
  tests/test_create.py
Labels: cla-signed

#13465 Type hints for conda.cli.main_search
  conda/cli/main_search.py
  news/13437-conda-cli-main_search-hints
Labels: cla-signed

#13445 Type hints and doc strings: conda.cli.main_info
  conda/cli/main_info.py
  news/13437-add-type-hints-main_info
Labels: cla-signed

#13478 Another round of `test_create.py` refactoring
  conda/base/context.py
  conda/testing/integration.py
  tests/cli/test_config.py
  tests/test-recipes/another_dependent/meta.yaml
  tests/test-recipes/noarch/another_dependent-1.0-0.tar.bz2
  tests/test-recipes/noarch/another_dependent-2.0-0.tar.bz2
  tests/test-recipes/noarch/other_dependent-1.0-0.tar.bz2
  tests/test-recipes/noarch/repodata.json
  tests/test-recipes/noarch/repodata.json.bz2
  tests/test-recipes/other_dependent/meta.yaml
  tests/test_create.py
Labels: cla-signed

#13460 Enable performance tracking via continuous benchmarking.
  .github/workflows/tests.yml
  README.md
  dev/linux/benchmarks.sh
  news/13460-benchmark-tracking
  pyproject.toml
  tests/cli/test_subcommands.py
  tests/core/test_solve.py
  tests/gateways/test_jlap.py
  tests/models/test_match_spec.py
Labels: cla-signed

#13485 Another test create batch
  tests/cli/test_main_run.py
  tests/cli/test_main_search.py
  tests/test_create.py
Labels: cla-signed

#13483 ensure `PackageRecord.timestamp` is dumped in milliseconds
  conda/testing/helpers.py
Labels: cla-signed

#13452 Enable repodata.json.zst by default
  conda/gateways/repodata/__init__.py
  conda/gateways/repodata/jlap/fetch.py
  conda/gateways/repodata/jlap/interface.py
  news/13256-repodata-json-zst
  tests/core/test_subdir_data.py
  tests/gateways/test_jlap.py
Labels: cla-signed

#13455 Improve repodata lock API
  conda/gateways/repodata/__init__.py
  news/repodata-lock-api
Labels: cla-signed

#13454 User guide refactors and updates
  docs/source/conf.py
  docs/source/glossary.rst
  docs/source/user-guide/concepts/channels.rst
  docs/source/user-guide/concepts/conda-commands.rst
  docs/source/user-guide/concepts/conda-performance.rst
  docs/source/user-guide/concepts/conda-plugins.rst
  docs/source/user-guide/concepts/environments.rst
  docs/source/user-guide/concepts/index.rst
  docs/source/user-guide/concepts/packages.rst
  docs/source/user-guide/concepts/pkg-specs.rst
  docs/source/user-guide/configuration/admin-multi-user-install.rst
  docs/source/user-guide/configuration/enable-tab-completion.rst
  docs/source/user-guide/configuration/index.rst
  docs/source/user-guide/configuration/sample-condarc.rst
  docs/source/user-guide/configuration/settings.rst
  docs/source/user-guide/configuration/use-condarc.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/install/download.rst
  docs/source/user-guide/install/index.rst
  docs/source/user-guide/install/linux.rst
  docs/source/user-guide/install/macos.rst
  docs/source/user-guide/install/rpm-debian.rst
  docs/source/user-guide/install/windows.rst
  docs/source/user-guide/tasks/create-custom-channels.rst
  docs/source/user-guide/tasks/creating-projects.rst
  docs/source/user-guide/tasks/index.rst
  docs/source/user-guide/tasks/manage-conda.rst
  docs/source/user-guide/tasks/manage-environments.rst
  docs/source/user-guide/tasks/manage-pkgs.rst
  docs/source/user-guide/tasks/manage-python.rst
  docs/source/user-guide/tasks/manage-virtual.rst
  docs/source/user-guide/tasks/view-command-line-help.rst
  docs/source/user-guide/troubleshooting.rst
Labels: cla-signed

#13489 More test_create refactoring
  tests/test_create.py
Labels: cla-signed

#13507 update `test_offline_with_empty_index_cache` for libmamba
  tests/test_create.py
Labels: cla-signed

#13511 Introducing `tmp_pkgs_dir` fixture
  conda/core/package_cache_data.py
  conda/testing/__init__.py
  conda/testing/integration.py
  news/13511-tmp_pkgs_dir
  tests/cli/test_main_clean.py
  tests/core/test_package_cache_data.py
  tests/test_create.py
Labels: cla-signed

#13387 Warn when an non-existent prefix path is specified for `rename`
  conda/cli/main_rename.py
  news/13387-warn-when-renaming-nonexistent-prefix
  tests/cli/test_main_rename.py
Labels: cla-signed

#13516 Update `test_metadata_cache_clearing`
  tests/core/test_subdir_data.py
Labels: cla-signed

#13494 `test_create` Updates/Refactoring
  tests/cli/test_compare.py
  tests/cli/test_main_info.py
  tests/cli/test_main_list.py
  tests/test_create.py
Labels: cla-signed, type::testing

#13521 allow None for cache-control header, interpret as 0
  conda/gateways/repodata/__init__.py
  news/no-cache-control
  tests/gateways/test_repodata_gateway.py
Labels: cla-signed

#13523 Refactor gawk tests, anaconda token tests, and index cache tests
  tests/cli/test_main_search.py
  tests/test_create.py
Labels: cla-signed

#13498 Create local `track_features`/`features` packages for testing
  conda/core/solve.py
  conda/testing/fixtures.py
  tests/test-recipes/feature_v1/meta.yaml
  tests/test-recipes/feature_v2/meta.yaml
  tests/test-recipes/noarch/feature-1.0-track_feature1_0.tar.bz2
  tests/test-recipes/noarch/feature-2.0-track_feature2_0.tar.bz2
  tests/test-recipes/noarch/repodata.json
  tests/test-recipes/noarch/repodata.json.bz2
  tests/test-recipes/noarch/track_feature-1.0-0.tar.bz2
  tests/test-recipes/noarch/track_feature-2.0-0.tar.bz2
  tests/test-recipes/track_feature_v1/meta.yaml
  tests/test-recipes/track_feature_v2/meta.yaml
  tests/test_create.py
  tests/test_features.py
Labels: cla-signed

#13524 Release 24.1.0
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/11545-move-content-trust-into-submodule
  news/13168-collapse-conda-env
  news/13190-getting-started-doc-updates
  news/13256-repodata-json-zst
  news/13315-skip-flexible-search-option
  news/13338-add-verify-to-env-location-action
  news/13384-add-goat-counter
  news/13387-warn-when-renaming-nonexistent-prefix
  news/13419-add-keep-env-flag
  news/13433-re-enable-pyupgrade-via-ruff
  news/13437-add-type-hints-main_info
  news/13437-conda-cli-main_search-hints
  news/13440-add-yn-prompt
  news/13460-benchmark-tracking
  news/13490-context-repodata-fns
  news/13491-no-repodata-zst-flag
  news/13511-tmp_pkgs_dir
  news/13517-userdata
  news/no-cache-control
  news/repodata-lock-api
Labels: cla-signed

#13518 Move / update more `test_create.py` tests
  tests/test_create.py
  tests/test_install.py
Labels: cla-signed

#13539 Fix test to work with `pytest 8.0.0`
  conda/__version__.py
  conda/gateways/connection/session.py
  conda/testing/fixtures.py
  tests/conftest.py
  tests/gateways/test_jlap.py
  tests/plugins/test_solvers.py
  tests/test_features.py
  tests/test_misc.py
Labels: cla-signed

#13530 Set `--use-repodata-zst` argument as `NULL`, rename `no_repodata_zst` to `use_repodata_zst`
  CHANGELOG.md
  conda/base/context.py
  conda/cli/helpers.py
  conda/gateways/repodata/__init__.py
  tests/gateways/test_jlap.py
Labels: cla-signed, in-progress
